USE K003_2

DECLARE 
@IDKATIOS CHAR(20) = 'DELTA'

IF OBJECT_ID('tempdb..#OperacionesFondeadoresTemporal') IS NOT NULL  
   BEGIN  
    DROP TABLE #OperacionesFondeadoresTemporal;
END
CREATE TABLE #OperacionesFondeadoresTemporal(
[FECHA_CORTE] VARCHAR(50) COLLATE Modern_Spanish_CI_AS
,[ESTADO_VENTA] VARCHAR(50) COLLATE Modern_Spanish_CI_AS
,[NO_VENTA] VARCHAR(50) COLLATE Modern_Spanish_CI_AS
,[LINEA VENTA] VARCHAR(50) COLLATE Modern_Spanish_CI_AS
,[NoCREDITO] VARCHAR(50) COLLATE Modern_Spanish_CI_AS
,[ESTADO_CREDITO] VARCHAR(50) COLLATE Modern_Spanish_CI_AS
,[NIT] VARCHAR(50) COLLATE Modern_Spanish_CI_AS
,[FONDEADOR] VARCHAR(300) COLLATE Modern_Spanish_CI_AS
,[CEDULA] VARCHAR(50) COLLATE Modern_Spanish_CI_AS
,[NOMBRE] VARCHAR(300) COLLATE Modern_Spanish_CI_AS
,[TASA_VENTA E.A.] DECIMAL(18,16)
,[TASA_VENTA M.V] DECIMAL(18,16)
,[TASA_CLIENTE E.A.] DECIMAL(18,16)
,[TASA_CLIENTE M.V] DECIMAL(18,16)
,[FECHA_VENTA] DATE
,[FECHA 0 VENTA] DATE
,[VR_VENTA] NUMERIC(18,2)
,[CAPITAL_VENDIDO] NUMERIC(18,2)
,[AJUSTE] NUMERIC(18,2)
,[CUOTAS_VENDIDAS] INT
,[CUOTA_FONDEADOR] NUMERIC(18,2)
,[P_PAGO_CLIENTE] DATE
,[P_PAGO_FONDEADOR] DATE
,[CUOTA_CTE] NUMERIC(18,2)
,[SEGUROS CUOTA] NUMERIC(18,2)
,[PGRACIA] NUMERIC(18,2)
,[CUENTAS POR COBRAR] NUMERIC(18,2)
,[CUOTA_TOTAL] NUMERIC(18,2)
,[SALDO_CAPITAL_FONDEADOR] NUMERIC(18,2)
,[SALDO CUOTA CAUSADA] NUMERIC(18,2)
,[CUOTAS_PAGADAS] INT
,[NPER FONDEADOR] INT
,[CAPITAL_CLIENTE] NUMERIC(18,2)
,[DIAS_VENCIDOS_FONDEADOR] INT
,[EDAD_MORA_CLIENTE] VARCHAR(100)
,[PORCENTAJE_PRIMA] NUMERIC(18,2)
,[PRIMA_ANTICIPADA] NUMERIC(18,2)
,[NoVENTA] VARCHAR(30)
)

INSERT INTO #OperacionesFondeadoresTemporal
SELECT
CONVERT(VARCHAR(10), GETDATE(), 120) AS 'FECHA_CORTE'
,ISNULL(PRE.IdEstado,'') AS 'ESTADO_VENTA'
,ISNULL(PRE.Ctivo,'0') AS 'NO_VENTA'
,ISNULL(PRE.Producto,'') AS 'LINEA VENTA'
,ISNULL(PRECLI.Ctivo,0) AS 'NoCREDITO'
,ISNULL(PRECLI.IdEstado,0) AS 'ESTADO_CREDITO'
,ISNULL(FON.NDoc,'') AS 'NIT'
,ISNULL(FON.Nombres,'') AS 'FONDEADOR'
,ISNULL(PER.NDoc,'') AS 'CEDULA'
,ISNULL(PER.Nombres,'') AS 'NOMBRE'
,ISNULL((POWER(CAST((1.000000+(PRE.Interes/100)) AS float),(12.000000)) - 1),0) AS 'TASA_VENTA E.A.'
,ISNULL((PRE.Interes / 100),0) AS 'TASA_VENTA M.V'
,ISNULL((POWER(CAST((1.000000+(PRECLI.Interes/100)) AS float),(12.000000)) - 1),0) AS 'TASA_CLIENTE E.A.'
,ISNULL((PRECLI.Interes / 100),0) AS 'TASA_CLIENTE M.V'
,ISNULL(PRE.FechaDesembolso,'') AS 'FECHA_VENTA'
,ISNULL(PRE.FechaInicial,'') AS 'FECHA 0 VENTA'
,ISNULL(PRE.CapitalSolicitado,0) AS 'VR_VENTA'
,ISNULL(PRE.CapitalInicial,0) AS 'CAPITAL_VENDIDO'
,ISNULL(INTI.Valor,0) AS 'AJUSTE'
,ISNULL(PRE.Plazo,0) AS 'CUOTAS_VENDIDAS'
,ISNULL(PRE.ValorCuotaTotal,0) AS 'CUOTA_FONDEADOR'
,DATEADD(MONTH,1,ISNULL(PRECLI.FechaInicial,'1900-01-01')) AS 'P_PAGO_CLIENTE'
,DATEADD(MONTH,1,ISNULL(PRE.FechaInicial,'1900-01-01')) AS 'P_PAGO_FONDEADOR'
,ISNULL(PRECLI.ValorCuotaCorriente,0) AS 'CUOTA_CTE'
,ISNULL(SEG.Valor,0) AS 'SEGUROS CUOTA'
,ISNULL(PG.Valor,0) AS 'PGRACIA'
,ISNULL(CRU.TOTAL,0)+ISNULL(CGM.TOTAL,0)+ISNULL(CIGM.TOTAL,0)+ISNULL(CII.TOTAL,0) AS 'CUENTAS POR COBRAR'
,ISNULL(PRECLI.ValorCuotaTotal,0) AS 'CUOTA_TOTAL'
,ISNULL(PS.SaldoCapital + PS.SCAK,0) AS 'SALDO_CAPITAL_FONDEADOR'
,ISNULL(PS.SCActual,0) AS 'SALDO CUOTA CAUSADA'
,ISNULL(PS.Cpagadas,0) AS 'CUOTAS_PAGADAS'
,ISNULL((dbo.NPER(PRE.INTERES/100,-PRE.ValorCuotaCorriente,PS.SaldoCapital+PS.SCAK,0,0)),0) AS 'NPER FONDEADOR'
,ISNULL((PSCLI.SaldoCapital+PSCLI.SCAK),0) AS 'CAPITAL_CLIENTE'
,ISNULL(PRE.DiasVencidos,0) AS 'DIAS_VENCIDOS_FONDEADOR'
,ISNULL(CASE WHEN PRECLI.DIASVENCIDOS <=0 THEN 'AL DIA' WHEN PRECLI.DIASVENCIDOS >=1 AND PRECLI.DIASVENCIDOS <=30 THEN '1 A 30' WHEN PRECLI.DIASVENCIDOS >=31 AND PRECLI.DIASVENCIDOS <=60 THEN '31 A 60' WHEN PRECLI.DIASVENCIDOS >=61 AND PRECLI.DIASVENCIDOS <=90 THEN '61 A 90' WHEN PRECLI.DIASVENCIDOS >=91 AND PRECLI.DIASVENCIDOS <=120 THEN '91 A 120' WHEN PRECLI.DIASVENCIDOS >=121 AND PRECLI.DIASVENCIDOS <=150 THEN '121 A 150' WHEN PRECLI.DIASVENCIDOS >=151 AND PRECLI.DIASVENCIDOS <=180 THEN '151 A 180' WHEN PRECLI.DIASVENCIDOS >=180 THEN 'MAYOR 180' END,0) AS 'EDAD_MORA_CLIENTE'
,ISNULL(PP.VALOR,0) AS 'PORCENTAJE_PRIMA'
,ISNULL(PA.VALOR,0) AS 'PRIMA_ANTICIPADA'
,ISNULL(NV.VALOR,0) AS 'NoVENTA'
FROM Prstms PRE WITH(NOLOCK)
INNER JOIN PrstmsSaldos PS WITH(NOLOCK) ON PRE.IdKatios=PS.IdKatios AND PRE.IdPrestamo=PS.IdPrestamo
LEFT JOIN ValoresCapturasDinamicas CRE WITH(NOLOCK) ON PRE.IdKatios=CRE.IdKatios AND PRE.Solicitud=CRE.NoProducto AND CRE.IdCaptura='TXT_IDPRESTAMOCLI'
LEFT JOIN ValoresCapturasDinamicas PP WITH(NOLOCK) ON PRE.IdKatios=PP.IdKatios AND PRE.Solicitud=PP.NoProducto AND PP.IdCaptura='TXT_PORPRIM'
LEFT JOIN ValoresCapturasDinamicas PA WITH(NOLOCK) ON PRE.IdKatios=PA.IdKatios AND PRE.Solicitud=PA.NoProducto AND PA.IdCaptura='TXT_PRIMAANT'
LEFT JOIN ValoresCapturasDinamicas NV WITH(NOLOCK) ON PRE.IdKatios=NV.IdKatios AND PRE.Solicitud=NV.NoProducto AND NV.IdCaptura='TXT_IDVENTA'
LEFT JOIN Prstms PRECLI WITH(NOLOCK) ON PRE.IdKatios=PRECLI.IdKatios AND CRE.Valor=PRECLI.IdPrestamo
LEFT JOIN PrstmsSaldos PSCLI WITH(NOLOCK) ON PRE.IdKatios=PSCLI.IdKatios AND PRECLI.IdPrestamo=PSCLI.IdPrestamo
LEFT JOIN PrestamosCargos SEG WITH(NOLOCK) ON PRE.IdKatios=SEG.IdKatios AND PRECLI.IdPrestamo=SEG.IdPrestamo AND SEG.Nombre='SEGURO'
LEFT JOIN PrestamosCargos PG WITH(NOLOCK) ON PRE.IdKatios=PG.IdKatios AND PRECLI.IdPrestamo=PG.IdPrestamo AND PG.Nombre='PGRACIA'
LEFT JOIN CONCEPTOSXFONDO CRU WITH(NOLOCK) ON PRE.IdKatios=CRU.IDKATIOS AND PRECLI.IdPrestamo=CRU.IdPrestamo AND CRU.NOMBRE='CXCRUNT' AND CRU.SIGLA='CXCRU'
LEFT JOIN CONCEPTOSXFONDO CGM WITH(NOLOCK) ON PRE.IdKatios=CGM.IDKATIOS AND PRECLI.IdPrestamo=CGM.IdPrestamo AND CGM.NOMBRE='CXCGARANTIASM' AND CGM.SIGLA='CXCGA'
LEFT JOIN CONCEPTOSXFONDO CIGM WITH(NOLOCK) ON PRE.IdKatios=CIGM.IDKATIOS AND PRECLI.IdPrestamo=CIGM.IdPrestamo AND CIGM.NOMBRE='CXCIVAGM' AND CIGM.SIGLA='CXCIV'
LEFT JOIN CONCEPTOSXFONDO CII WITH(NOLOCK) ON PRE.IdKatios=CII.IDKATIOS AND PRECLI.IdPrestamo=CII.IdPrestamo AND CII.NOMBRE='CXCINTINICIALES' AND CII.SIGLA='CXCIN'
LEFT JOIN Personas FON WITH(NOLOCK) ON PRE.IdKatios=FON.IdKatios AND PRE.TDocFondeador=FON.TDoc AND PRE.NDocForndedador=FON.NDoc
LEFT JOIN Personas PER WITH(NOLOCK) ON PRE.IdKatios=PER.IdKatios AND PRE.TDoc=PER.TDoc AND PRE.NDoc=PER.NDoc
LEFT JOIN PrestamosCargos INTI WITH(NOLOCK) ON PRE.IdKatios=INTI.IdKatios AND PRE.IdPrestamo=INTI.IdPrestamo AND INTI.Nombre='INTINICIALES'
WHERE PRE.IdKatios=@IDKATIOS
AND PRE.Producto IN ('Venta Cuota Creciente','Venta de Flujos')


CREATE TABLE OperacionesFondeadores(
[FECHA_CORTE] VARCHAR(50) COLLATE Modern_Spanish_CI_AS
,[ESTADO_VENTA] VARCHAR(50) COLLATE Modern_Spanish_CI_AS
,[NO_VENTA] VARCHAR(50) COLLATE Modern_Spanish_CI_AS
,[LINEA VENTA] VARCHAR(50) COLLATE Modern_Spanish_CI_AS
,[NoCREDITO] VARCHAR(50) COLLATE Modern_Spanish_CI_AS
,[ESTADO_CREDITO] VARCHAR(50) COLLATE Modern_Spanish_CI_AS
,[NIT] VARCHAR(50) COLLATE Modern_Spanish_CI_AS
,[FONDEADOR] VARCHAR(300) COLLATE Modern_Spanish_CI_AS
,[CEDULA] VARCHAR(50) COLLATE Modern_Spanish_CI_AS
,[NOMBRE] VARCHAR(300) COLLATE Modern_Spanish_CI_AS
,[TASA_VENTA E.A.] DECIMAL(18,16)
,[TASA_VENTA M.V] DECIMAL(18,16)
,[TASA_CLIENTE E.A.] DECIMAL(18,16)
,[TASA_CLIENTE M.V] DECIMAL(18,16)
,[DIFERENCIA_DIAS] NUMERIC(18,0)
,[FECHA_VENTA] DATE
,[FECHA 0 VENTA] DATE
,[VR_VENTA] NUMERIC(18,2)
,[CAPITAL_VENDIDO] NUMERIC(18,2)
,[AJUSTE] NUMERIC(18,2)
,[CUOTAS_VENDIDAS] INT
,[CUOTA_FONDEADOR] NUMERIC(18,2)
,[P_PAGO_CLIENTE] DATE
,[P_PAGO_FONDEADOR] DATE
,[CUOTA_CTE] NUMERIC(18,2)
,[SEGUROS CUOTA] NUMERIC(18,2)
,[PGRACIA] NUMERIC(18,2)
,[CUENTAS POR COBRAR] NUMERIC(18,2)
,[CUOTA_TOTAL] NUMERIC(18,2)
,[SALDO_CAPITAL_FONDEADOR] NUMERIC(18,2)
,[SALDO CUOTA CAUSADA] NUMERIC(18,2)
,[CUOTAS_PAGADAS] INT
,[NPER FONDEADOR] INT
,[CAPITAL_CLIENTE] NUMERIC(18,2)
,[DIAS_VENCIDOS_FONDEADOR] INT
,[EDAD_MORA_CLIENTE] VARCHAR(100)
,[PORCENTAJE_PRIMA] NUMERIC(18,2)
,[PRIMA_ANTICIPADA] NUMERIC(18,2)
,[NoVENTA] VARCHAR(30)
)

INSERT INTO OperacionesFondeadores
SELECT
opf."FECHA_CORTE" AS 'FECHA_CORTE'
,opf."ESTADO_VENTA" AS 'ESTADO_VENTA'
,opf."NO_VENTA" AS 'NO_VENTA'
,opf."LINEA VENTA" AS 'LINEA VENTA'
,opf."NoCREDITO" AS 'NoCREDITO'
,opf."ESTADO_CREDITO" AS 'ESTADO_CREDITO'
,opf."NIT" AS 'NIT'
,opf."FONDEADOR" AS 'FONDEADOR'
,opf."CEDULA" AS 'CEDULA'
,opf."NOMBRE" AS 'NOMBRE'
,opf."TASA_VENTA E.A." AS 'TASA_VENTA E.A.'
,opf."TASA_VENTA M.V" AS 'TASA_VENTA M.V'
,opf."TASA_CLIENTE E.A." AS 'TASA_CLIENTE E.A.'
,opf."TASA_CLIENTE M.V" AS 'TASA_CLIENTE M.V'
,DATEDIFF(DAY, opf."FECHA_VENTA", opf."P_PAGO_FONDEADOR") AS 'DIFERENCIA_DIAS'
,opf."FECHA_VENTA" AS 'FECHA_VENTA'
,opf."FECHA 0 VENTA" AS 'FECHA 0 VENTA'
,opf."VR_VENTA" AS 'VR_VENTA'
,opf."CAPITAL_VENDIDO" AS 'CAPITAL_VENDIDO'
,opf."AJUSTE" AS 'AJUSTE'
,opf."CUOTAS_VENDIDAS" AS 'CUOTAS_VENDIDAS'
,opf."CUOTA_FONDEADOR" AS 'CUOTA_FONDEADOR'
,opf."P_PAGO_CLIENTE" AS 'P_PAGO_CLIENTE'
,opf."P_PAGO_FONDEADOR" AS 'P_PAGO_FONDEADOR'
,opf."CUOTA_CTE" AS 'CUOTA_CTE'
,opf."SEGUROS CUOTA" AS 'SEGUROS CUOTA'
,opf."PGRACIA" AS 'PGRACIA'
,opf."CUENTAS POR COBRAR" AS 'CUENTAS POR COBRAR'
,opf."CUOTA_TOTAL" AS 'CUOTA_TOTAL'
,opf."SALDO_CAPITAL_FONDEADOR" AS 'SALDO_CAPITAL_FONDEADOR'
,opf."SALDO CUOTA CAUSADA" AS 'SALDO CUOTA CAUSADA'
,opf."CUOTAS_PAGADAS" AS 'CUOTAS_PAGADAS'
,opf."NPER FONDEADOR" AS 'NPER FONDEADOR'
,opf."CAPITAL_CLIENTE" AS 'CAPITAL_CLIENTE'
,opf."DIAS_VENCIDOS_FONDEADOR" AS 'DIAS_VENCIDOS_FONDEADOR'
,opf."EDAD_MORA_CLIENTE" AS 'EDAD_MORA_CLIENTE'
,opf."PORCENTAJE_PRIMA" AS 'PORCENTAJE_PRIMA'
,opf."PRIMA_ANTICIPADA" AS 'PRIMA_ANTICIPADA'
,opf."NoVENTA" AS 'NoVENTA'
FROM #OperacionesFondeadoresTemporal opf WITH(NOLOCK)

