USE K003
BEGIN

DECLARE @IDKATIOS  CHAR(20),
       @FechaInicial DATE,
       @FechaFinal DATE,
	   @TConsulta CHAR(100),
	   @MES VARCHAR(5) = SUBSTRING(CONVERT(VARCHAR(10), GETDATE(), 120),6,2),
       @MESANTERIOR INT

SET @IDKATIOS = 'DELTA'

IF @MES != '01'
	SET @MESANTERIOR = CONVERT(INT, @MES)-1;
ELSE 
	SET @MESANTERIOR = CONVERT(INT, @MES)+11;

SET @MES = CONVERT(VARCHAR, @MESANTERIOR);

IF LEN(@MES) = 1
	SET @MES = '0'+@MES

SET	@FechaInicial = LEFT (CONVERT(VARCHAR(10), GETDATE(), 120),5) + @MES + '-01'
SET	@FechaFinal = LEFT (CONVERT(VARCHAR(10), GETDATE(), 120),5) + @MES + '-' + RIGHT(EOMONTH(@FechaInicial),2)

SET	@TConsulta = 'FECHA_EFECTIVA'

IF OBJECT_ID('tempdb..#LIQUIDACION') IS NOT NULL  
BEGIN  
DROP TABLE #LIQUIDACION;
END
CREATE TABLE #LIQUIDACION (
[IDKATIOS] VARCHAR(20) COLLATE Modern_Spanish_CI_AS
,[IDDIARIO] VARCHAR(100) COLLATE Modern_Spanish_CI_AS 
,[IDLIQUIDACION] VARCHAR (100) COLLATE Modern_Spanish_CI_AS
)

IF OBJECT_ID('tempdb..#SALDOSLIQUIDACION') IS NOT NULL  
BEGIN  
DROP TABLE #SALDOSLIQUIDACION;
END
CREATE TABLE #SALDOSLIQUIDACION (
[IDKATIOS] VARCHAR(20) COLLATE Modern_Spanish_CI_AS
,[IDDIARIO] VARCHAR(100) COLLATE Modern_Spanish_CI_AS
,[IDLIQUIDACION] VARCHAR(100) COLLATE Modern_Spanish_CI_AS 
,[CONCEPTO] VARCHAR (100) COLLATE Modern_Spanish_CI_AS
,[VALOR] NUMERIC(18,2)
,[CONDONACION] NUMERIC(18,2)
)

IF OBJECT_ID('tempdb..#CAPITALPAGADO') IS NOT NULL  
BEGIN  
DROP TABLE #CAPITALPAGADO;
END
CREATE TABLE #CAPITALPAGADO (
[IDKATIOS] VARCHAR(20) COLLATE Modern_Spanish_CI_AS
,[IDDIARIO] VARCHAR(100) COLLATE Modern_Spanish_CI_AS
,[VALOR] NUMERIC(18,0)
,[CONDONACION] NUMERIC(18,0)
)

IF OBJECT_ID('tempdb..#KPAGADOXCUOTAVENCIDA') IS NOT NULL  
BEGIN  
DROP TABLE #KPAGADOXCUOTAVENCIDA;
END
CREATE TABLE #KPAGADOXCUOTAVENCIDA (
[IDKATIOS] VARCHAR(20) COLLATE Modern_Spanish_CI_AS
,[IDPRESTAMO] VARCHAR(100) COLLATE Modern_Spanish_CI_AS
,[IDDIARIO] VARCHAR(100) COLLATE Modern_Spanish_CI_AS
,[KPAGADOVENC] NUMERIC(18,2)
)

IF OBJECT_ID('tempdb..#KPAGADOXCUOTANOVENCIDA') IS NOT NULL  
BEGIN  
DROP TABLE #KPAGADOXCUOTANOVENCIDA;
END
CREATE TABLE #KPAGADOXCUOTANOVENCIDA (
[IDKATIOS] VARCHAR(20) COLLATE Modern_Spanish_CI_AS
,[IDPRESTAMO] VARCHAR(100) COLLATE Modern_Spanish_CI_AS
,[IDDIARIO] VARCHAR(100) COLLATE Modern_Spanish_CI_AS
,[KPAGADONOVENC] NUMERIC(18,2)
)

IF OBJECT_ID('tempdb..#INTERESPAGADO') IS NOT NULL  
BEGIN  
DROP TABLE #INTERESPAGADO;
END
CREATE TABLE #INTERESPAGADO (
[IDKATIOS] VARCHAR(20) COLLATE Modern_Spanish_CI_AS
,[IDDIARIO] VARCHAR(100) COLLATE Modern_Spanish_CI_AS
,[VALOR] NUMERIC(18,0)
,[CONDONACION] NUMERIC(18,0)
)

IF OBJECT_ID('tempdb..#INTFINALES') IS NOT NULL  
BEGIN  
DROP TABLE #INTFINALES;
END
CREATE TABLE #INTFINALES (
[IDKATIOS] VARCHAR(20) COLLATE Modern_Spanish_CI_AS
,[IDDIARIO] VARCHAR(100) COLLATE Modern_Spanish_CI_AS
,[VALOR] NUMERIC(18,0)
,[CONDONACION] NUMERIC(18,0)
)

IF OBJECT_ID('tempdb..#IVENCIDO') IS NOT NULL  
BEGIN  
DROP TABLE #IVENCIDO;
END
CREATE TABLE #IVENCIDO (
[IDKATIOS] VARCHAR(20) COLLATE Modern_Spanish_CI_AS
,[IDPRESTAMO] VARCHAR(100) COLLATE Modern_Spanish_CI_AS
,[IDDIARIO] VARCHAR(100) COLLATE Modern_Spanish_CI_AS
,[VALOR] NUMERIC(18,2)
)

IF OBJECT_ID('tempdb..#IFACTURADO') IS NOT NULL  
BEGIN  
DROP TABLE #IFACTURADO;
END
CREATE TABLE #IFACTURADO (
[IDKATIOS] VARCHAR(20) COLLATE Modern_Spanish_CI_AS
,[IDPRESTAMO] VARCHAR(100) COLLATE Modern_Spanish_CI_AS
,[IDDIARIO] VARCHAR(100) COLLATE Modern_Spanish_CI_AS
,[VALOR] NUMERIC(18,2)
)

IF OBJECT_ID('tempdb..#SEGUROPAGADO') IS NOT NULL  
BEGIN  
DROP TABLE #SEGUROPAGADO;
END
CREATE TABLE #SEGUROPAGADO (
[IDKATIOS] VARCHAR(20) COLLATE Modern_Spanish_CI_AS
,[IDDIARIO] VARCHAR(100) COLLATE Modern_Spanish_CI_AS
,[VALOR] NUMERIC(18,0)
,[CONDONACION] NUMERIC(18,0)
)

IF OBJECT_ID('tempdb..#GPSPAGADO') IS NOT NULL  
BEGIN  
DROP TABLE #GPSPAGADO;
END
CREATE TABLE #GPSPAGADO (
[IDKATIOS] VARCHAR(20) COLLATE Modern_Spanish_CI_AS
,[IDDIARIO] VARCHAR(100) COLLATE Modern_Spanish_CI_AS
,[VALOR] NUMERIC(18,0)
,[CONDONACION] NUMERIC(18,0)
)


IF OBJECT_ID('tempdb..#MORAPAGADO') IS NOT NULL  
BEGIN  
DROP TABLE #MORAPAGADO;
END
CREATE TABLE #MORAPAGADO (
[IDKATIOS] VARCHAR(20) COLLATE Modern_Spanish_CI_AS
,[IDDIARIO] VARCHAR(100) COLLATE Modern_Spanish_CI_AS
,[VALOR] NUMERIC(18,0)
,[CONDONACION] NUMERIC(18,0)
)

IF OBJECT_ID('tempdb..#GACPAGADO') IS NOT NULL  
BEGIN  
DROP TABLE #GACPAGADO;
END
CREATE TABLE #GACPAGADO (
[IDKATIOS] VARCHAR(20) COLLATE Modern_Spanish_CI_AS
,[IDDIARIO] VARCHAR(100) COLLATE Modern_Spanish_CI_AS
,[VALOR] NUMERIC(18,0)
,[CONDONACION] NUMERIC(18,0)
)

IF OBJECT_ID('tempdb..#IVAGACPAGADO') IS NOT NULL  
BEGIN  
DROP TABLE #IVAGACPAGADO;
END
CREATE TABLE #IVAGACPAGADO (
[IDKATIOS] VARCHAR(20) COLLATE Modern_Spanish_CI_AS
,[IDDIARIO] VARCHAR(100) COLLATE Modern_Spanish_CI_AS
,[VALOR] NUMERIC(18,0)
,[CONDONACION] NUMERIC(18,0)
)

IF OBJECT_ID('tempdb..#CXCPGRACIA') IS NOT NULL  
BEGIN  
DROP TABLE #CXCPGRACIA;
END
CREATE TABLE #CXCPGRACIA (
[IDKATIOS] VARCHAR(20) COLLATE Modern_Spanish_CI_AS
,[IDDIARIO] VARCHAR(100) COLLATE Modern_Spanish_CI_AS
,[VALOR] NUMERIC(18,0)
,[CONDONACION] NUMERIC(18,0)
)

IF OBJECT_ID('tempdb..#CXCCGPS') IS NOT NULL  
BEGIN  
DROP TABLE #CXCCGPS;
END
CREATE TABLE #CXCCGPS (
[IDKATIOS] VARCHAR(20) COLLATE Modern_Spanish_CI_AS
,[IDDIARIO] VARCHAR(100) COLLATE Modern_Spanish_CI_AS
,[VALOR] NUMERIC(18,0)
,[CONDONACION] NUMERIC(18,0)
)


IF OBJECT_ID('tempdb..#SALDOAFAVORPAGADO') IS NOT NULL  
BEGIN  
DROP TABLE #SALDOAFAVORPAGADO;
END
CREATE TABLE #SALDOAFAVORPAGADO (
[IDKATIOS] VARCHAR(20) COLLATE Modern_Spanish_CI_AS
,[IDDIARIO] VARCHAR(100) COLLATE Modern_Spanish_CI_AS
,[VALOR] NUMERIC(18,0)
,[CONDONACION] NUMERIC(18,0)
)

IF OBJECT_ID('tempdb..#CXCRUNT') IS NOT NULL  
BEGIN  
DROP TABLE #CXCRUNT;
END
CREATE TABLE #CXCRUNT (
[IDKATIOS] VARCHAR(20) COLLATE Modern_Spanish_CI_AS
,[IDDIARIO] VARCHAR(100) COLLATE Modern_Spanish_CI_AS
,[VALOR] NUMERIC(18,0)
,[CONDONACION] NUMERIC(18,0)
)

IF OBJECT_ID('tempdb..#CXCGARANTIASM') IS NOT NULL  
BEGIN  
DROP TABLE #CXCGARANTIASM;
END
CREATE TABLE #CXCGARANTIASM (
[IDKATIOS] VARCHAR(20) COLLATE Modern_Spanish_CI_AS
,[IDDIARIO] VARCHAR(100) COLLATE Modern_Spanish_CI_AS
,[VALOR] NUMERIC(18,0)
,[CONDONACION] NUMERIC(18,0)
)

IF OBJECT_ID('tempdb..#CXCIVAGARANTIAS') IS NOT NULL  
BEGIN  
DROP TABLE #CXCIVAGARANTIAS;
END
CREATE TABLE #CXCIVAGARANTIAS (
[IDKATIOS] VARCHAR(20) COLLATE Modern_Spanish_CI_AS
,[IDDIARIO] VARCHAR(100) COLLATE Modern_Spanish_CI_AS
,[VALOR] NUMERIC(18,0)
,[CONDONACION] NUMERIC(18,0)
)

IF OBJECT_ID('tempdb..#CXCIINICIALES') IS NOT NULL  
BEGIN  
DROP TABLE #CXCIINICIALES;
END
CREATE TABLE #CXCIINICIALES (
[IDKATIOS] VARCHAR(20) COLLATE Modern_Spanish_CI_AS
,[IDDIARIO] VARCHAR(100) COLLATE Modern_Spanish_CI_AS
,[VALOR] NUMERIC(18,0)
,[CONDONACION] NUMERIC(18,0)
)

IF OBJECT_ID('tempdb..#CAPITALMORA') IS NOT NULL  
BEGIN  
DROP TABLE #CAPITALMORA;
END
CREATE TABLE #CAPITALMORA (
[IDKATIOS] VARCHAR(20) COLLATE Modern_Spanish_CI_AS
,[IDDIARIO] VARCHAR(100) COLLATE Modern_Spanish_CI_AS
,[VALOR] NUMERIC(18,0)
)

IF OBJECT_ID('tempdb..#EDADMORA') IS NOT NULL  
BEGIN  
DROP TABLE #EDADMORA;
END
CREATE TABLE #EDADMORA (
[IDKATIOS] VARCHAR(20) COLLATE Modern_Spanish_CI_AS
,[IDDIARIO] VARCHAR(100) COLLATE Modern_Spanish_CI_AS
,[DMORA] VARCHAR(100) COLLATE Modern_Spanish_CI_AS
,[EDAD] NUMERIC(18,0)
,[EDADMORA] VARCHAR (100) COLLATE Modern_Spanish_CI_AS
)

IF OBJECT_ID('tempdb..#AplicacionPagosTemporal') IS NOT NULL  
BEGIN  
DROP TABLE #AplicacionPagosTemporal;
END
CREATE TABLE #AplicacionPagosTemporal (
[FECHA_APLICACION] DATE
,[CREDITO] VARCHAR(100)
,[DOCUMENTO] VARCHAR(100)
,[TITULAR] VARCHAR(500)
,[CUENTA_RECAUDO] VARCHAR(500)
,[FECHA_PAGO] DATE
,[TRANSACCION] VARCHAR(500)
,[VALOR_PAGADO] NUMERIC(18,2)
,[KPAGADO] NUMERIC(18,2)
,[IPAGADO] NUMERIC(18,2)
,[SEGURO] NUMERIC(18,2)
,[MORA] NUMERIC(18,2)
,[GASTOS_DE_COBRANZA] NUMERIC(18,2)
,[IVAGAC] NUMERIC(18,2)
,[CXCPGRACIA] NUMERIC(18,2)
,[SAFAVOR] NUMERIC(18,2)
,[RUNT] NUMERIC(18,2)
,[GARANTIAS_MOBILIARIAS] NUMERIC(18,2)
,[IVA_GARANTIAS_MOBILIARIAS] NUMERIC(18,2)
,[GPS_PAGADO] NUMERIC(18,2)
,[I_INICALES] NUMERIC(18,2)
,[KFACTURADO_VENCIDO] NUMERIC(18,2)
,[KFACTURADO_NO_VENCIDO] NUMERIC(18,2)
,[KNO_FACTURADO] NUMERIC(18,2)
,[CAPITAL_MORA] NUMERIC(18,2)
,[IVENCIDO] NUMERIC(18,2)
,[IFACTURADO] NUMERIC(18,2)
,[CUOTAS] VARCHAR(MAX)
,[ESTADO] VARCHAR(500)
,[SUBESTADO] VARCHAR(100)
,[EDAD_MORA] VARCHAR(500)
,[PRODUCTO] VARCHAR(500)
,[CONSECUTIVO] VARCHAR(500)
,[REFERENCIA] VARCHAR(MAX)
,[INT_FINALES] NUMERIC(18,2)
)

END

INSERT INTO #LIQUIDACION
SELECT
PRE.IDKATIOS
,DRO.IDDIARIO
,PD.ESTADO
FROM PRSTMS PRE WITH(NOLOCK)
INNER JOIN PRSTMSENC PE WITH(NOLOCK) ON PRE.IDKATIOS=PE.IDKATIOS AND PRE.IDPRESTAMO=PE.IDPRODUCTO AND PE.IDTRX IN ('5023') AND PE.REFERENCIA NOT LIKE '%RV%'
INNER JOIN DIARIO DRO WITH(NOLOCK) ON PRE.IDKATIOS=DRO.IDKATIOS AND PE.IDDIARIO=DRO.IDDIARIO AND DRO.TIPOTRX<>'RV'
INNER JOIN PRSTMSDETALLE PD WITH(NOLOCK) ON PRE.IDKATIOS=PD.IDKATIOS AND PE.IDDIARIO=PD.IDDIARIO AND PE.IDENCABEZADO=PD.IDENCABEZADO AND PD.NOMBRECUENTA IN ('IDProcPagoLiquidacion')
WHERE PRE.IDKATIOS=@IDKATIOS 
AND PRE.PRODUCTO NOT IN ('Venta Cuota Creciente','Venta de Flujos')
AND (CASE WHEN @TConsulta='FECHA_EFECTIVA' THEN CAST(DRO.FECHAEFECTIVA AS DATE) WHEN @TConsulta='FECHA_APLICACION' THEN CAST(DRO.FECHADIA AS DATE) END) BETWEEN @FECHAINICIAL AND @FECHAFINAL

INSERT INTO #SALDOSLIQUIDACION
SELECT
LQ.IDKATIOS
,LQ.IDDIARIO
,LQ.IDLIQUIDACION
,PLD.CONCEPTO
,SUM(PLD.VALOR)
,SUM(PLD.CONDONACION)
FROM #LIQUIDACION LQ WITH(NOLOCK)
INNER JOIN PRSTMSLIQUIDACIONDETALLE PLD WITH(NOLOCK) ON LQ.IDKATIOS=PLD.IDKATIOS AND LQ.IDLIQUIDACION=PLD.IDLIQUIDACION
WHERE LQ.IDKATIOS=@IDKATIOS
GROUP BY LQ.IDKATIOS,LQ.IDDIARIO,LQ.IDLIQUIDACION,PLD.CONCEPTO

INSERT INTO #CAPITALPAGADO
SELECT
PRE.IDKATIOS
,DRO.IDDIARIO
,CASE WHEN LQ.IDLIQUIDACION IS NULL THEN SUM(PD.VALOR) ELSE ISNULL(LQ.VALOR,0)+ISNULL(LQ2.VALOR,0)-ISNULL(LQ.CONDONACION,0)-ISNULL(LQ2.CONDONACION,0) END
,CASE WHEN LQ.IDLIQUIDACION IS NULL THEN 0 ELSE ISNULL(LQ.CONDONACION,0)-ISNULL(LQ2.CONDONACION,0) END
FROM PRSTMS PRE WITH(NOLOCK)
INNER JOIN PRSTMSENC PE WITH(NOLOCK) ON PRE.IDKATIOS=PE.IDKATIOS AND PRE.IDPRESTAMO=PE.IDPRODUCTO AND PE.IDTRX IN ('5001', '5002', '5003','5013','5014','5015','5021') AND PE.REFERENCIA NOT LIKE '%RV%' AND PE.REFERENCIA <>'Adicion de observacion de cobranza'
INNER JOIN DIARIO DRO WITH(NOLOCK) ON PRE.IDKATIOS=DRO.IDKATIOS AND PE.IDDIARIO=DRO.IDDIARIO AND DRO.TIPOTRX<>'RV'
INNER JOIN PRSTMSDETALLE PD WITH(NOLOCK) ON PRE.IDKATIOS=PD.IDKATIOS AND PE.IDDIARIO=PD.IDDIARIO AND PE.IDENCABEZADO=PD.IDENCABEZADO AND PD.NOMBRECUENTA IN ('KPAGADO')
LEFT JOIN #SALDOSLIQUIDACION LQ WITH(NOLOCK) ON PRE.IDKATIOS=LQ.IDKATIOS AND PE.IDDIARIO=LQ.IDDIARIO AND LQ.CONCEPTO='CAPITAL'
LEFT JOIN #SALDOSLIQUIDACION LQ2 WITH(NOLOCK) ON PRE.IDKATIOS=LQ2.IDKATIOS AND PE.IDDIARIO=LQ2.IDDIARIO AND LQ2.CONCEPTO='SALDOCAPITAL'
WHERE PRE.IDKATIOS=@IDKATIOS 
AND PRE.PRODUCTO NOT IN ('Venta Cuota Creciente','Venta de Flujos')
AND (CASE WHEN @TConsulta='FECHA_EFECTIVA' THEN CAST(DRO.FECHAEFECTIVA AS DATE) WHEN @TConsulta='FECHA_APLICACION' THEN CAST(DRO.FECHADIA AS DATE) END) BETWEEN @FECHAINICIAL AND @FECHAFINAL
GROUP BY PRE.IDKATIOS,DRO.IDDIARIO,LQ.CONDONACION,LQ.VALOR,LQ.IDLIQUIDACION,LQ2.VALOR,LQ2.CONDONACION

INSERT INTO #KPAGADOXCUOTAVENCIDA
SELECT 
PE.Idkatios IDKATIOS
,PE.IdProducto IDPRESTAMO
,PE.IdDiario IDDIARIO
,ISNULL(SUM(PDKMORA.VALOR),0) KPAGADOCUOTA
FROM #CAPITALPAGADO KP WITH(NOLOCK)
INNER JOIN PRSTMSENC PE WITH(NOLOCK) ON KP.IDKATIOS=PE.Idkatios AND KP.IDDIARIO=PE.IdDiario
INNER JOIN PrstmsDetalle PDDM WITH(NOLOCK) ON PE.Idkatios=PDDM.IDKATIOS AND PE.IdProducto=PDDM.IDPRESTAMO AND PE.IdDiario=PDDM.IDDIARIO AND PE.IdEncabezado=PDDM.IDENCABEZADO AND PDDM.NOMBRECUENTA='DIASMORA' AND PDDM.VALOR>0
LEFT JOIN PrstmsDetalle PDKMORA WITH(NOLOCK) ON PE.Idkatios=PDKMORA.IDKATIOS AND PE.IdProducto=PDKMORA.IDPRESTAMO AND PDDM.IdDiario=PDKMORA.IDDIARIO AND PDDM.IdEncabezado=PDKMORA.IDENCABEZADO AND PDKMORA.NOMBRECUENTA='KPAGADO'
WHERE PE.IDKATIOS=@IDKATIOS 
GROUP BY PE.Idkatios,PE.IdProducto,PE.IdDiario

INSERT INTO #KPAGADOXCUOTANOVENCIDA
SELECT 
PE.Idkatios IDKATIOS
,PE.IdProducto IDPRESTAMO
,PE.IdDiario IDDIARIO
,ISNULL(SUM(PDKMORA.VALOR),0) KPAGADONOVENC
FROM #CAPITALPAGADO KP WITH(NOLOCK)
INNER JOIN PRSTMSENC PE WITH(NOLOCK) ON KP.IDKATIOS=PE.Idkatios AND KP.IDDIARIO=PE.IdDiario
INNER JOIN PrstmsDetalle PDDM WITH(NOLOCK) ON PE.Idkatios=PDDM.IDKATIOS AND PE.IdProducto=PDDM.IDPRESTAMO AND PE.IdDiario=PDDM.IDDIARIO AND PE.IdEncabezado=PDDM.IDENCABEZADO AND PDDM.NOMBRECUENTA='DIASMORA' AND PDDM.VALOR<=0
LEFT JOIN PrstmsDetalle PDKMORA WITH(NOLOCK) ON PE.Idkatios=PDKMORA.IDKATIOS AND PE.IdProducto=PDKMORA.IDPRESTAMO AND PDDM.IdDiario=PDKMORA.IDDIARIO AND PDDM.IdEncabezado=PDKMORA.IDENCABEZADO AND PDKMORA.NOMBRECUENTA='KPAGADO'
WHERE PE.IDKATIOS=@IDKATIOS
GROUP BY PE.Idkatios,PE.IdProducto,PE.IdDiario

INSERT INTO #INTERESPAGADO
SELECT
PRE.IDKATIOS
,DRO.IDDIARIO
,CASE WHEN LQ.IDLIQUIDACION IS NULL THEN SUM(PD.VALOR) ELSE ISNULL(LQ.VALOR,0)+ISNULL(LQ2.VALOR,0)-ISNULL(LQ.CONDONACION,0)-ISNULL(LQ2.CONDONACION,0) END
,CASE WHEN LQ.IDLIQUIDACION IS NULL THEN 0 ELSE ISNULL(LQ.CONDONACION,0)-ISNULL(LQ2.CONDONACION,0) END
FROM PRSTMS PRE WITH(NOLOCK)
INNER JOIN PRSTMSENC PE WITH(NOLOCK) ON PRE.IDKATIOS=PE.IDKATIOS AND PRE.IDPRESTAMO=PE.IDPRODUCTO AND PE.IDTRX IN ('5001', '5002', '5003','5013','5014','5015','5021') AND PE.REFERENCIA NOT LIKE '%RV%' AND PE.REFERENCIA <>'Adicion de observacion de cobranza'
INNER JOIN DIARIO DRO WITH(NOLOCK) ON PRE.IDKATIOS=DRO.IDKATIOS AND PE.IDDIARIO=DRO.IDDIARIO AND DRO.TIPOTRX<>'RV'
INNER JOIN PRSTMSDETALLE PD WITH(NOLOCK) ON PRE.IDKATIOS=PD.IDKATIOS AND PE.IDDIARIO=PD.IDDIARIO AND PE.IDENCABEZADO=PD.IDENCABEZADO AND PD.NOMBRECUENTA IN ('IPAGADO')
LEFT JOIN #SALDOSLIQUIDACION LQ WITH(NOLOCK) ON PRE.IDKATIOS=LQ.IDKATIOS AND PE.IDDIARIO=LQ.IDDIARIO AND LQ.CONCEPTO='INTERES'
LEFT JOIN #SALDOSLIQUIDACION LQ2 WITH(NOLOCK) ON PRE.IDKATIOS=LQ2.IDKATIOS AND PE.IDDIARIO=LQ2.IDDIARIO AND LQ2.CONCEPTO='INTFINAL'
WHERE PRE.IDKATIOS=@IDKATIOS 
AND PRE.PRODUCTO NOT IN ('Venta Cuota Creciente','Venta de Flujos')
AND (CASE WHEN @TConsulta='FECHA_EFECTIVA' THEN CAST(DRO.FECHAEFECTIVA AS DATE) WHEN @TConsulta='FECHA_APLICACION' THEN CAST(DRO.FECHADIA AS DATE) END) BETWEEN @FECHAINICIAL AND @FECHAFINAL
GROUP BY PRE.IDKATIOS,DRO.IDDIARIO,LQ.CONDONACION,LQ.VALOR,LQ.IDLIQUIDACION,LQ2.VALOR,LQ2.CONDONACION

INSERT INTO #INTFINALES
SELECT
PRE.IDKATIOS
,DRO.IDDIARIO
,CASE WHEN LQ.IDLIQUIDACION IS NULL THEN SUM(PD.VALOR) ELSE ISNULL(LQ.VALOR,0)+ISNULL(LQ2.VALOR,0)-ISNULL(LQ.CONDONACION,0)-ISNULL(LQ2.CONDONACION,0) END
,CASE WHEN LQ.IDLIQUIDACION IS NULL THEN 0 ELSE ISNULL(LQ.CONDONACION,0)-ISNULL(LQ2.CONDONACION,0) END
FROM PRSTMS PRE WITH(NOLOCK)
INNER JOIN PRSTMSENC PE WITH(NOLOCK) ON PRE.IDKATIOS=PE.IDKATIOS AND PRE.IDPRESTAMO=PE.IDPRODUCTO AND PE.IDTRX IN ('5001', '5002', '5003','5013','5014','5015','5021') AND PE.REFERENCIA NOT LIKE '%RV%' AND PE.REFERENCIA <>'Adicion de observacion de cobranza'
INNER JOIN DIARIO DRO WITH(NOLOCK) ON PRE.IDKATIOS=DRO.IDKATIOS AND PE.IDDIARIO=DRO.IDDIARIO AND DRO.TIPOTRX<>'RV'
INNER JOIN PRSTMSDETALLE PD WITH(NOLOCK) ON PRE.IDKATIOS=PD.IDKATIOS AND PE.IDDIARIO=PD.IDDIARIO AND PE.IDENCABEZADO=PD.IDENCABEZADO AND PD.NOMBRECUENTA IN ('InteresTotal')
LEFT JOIN #SALDOSLIQUIDACION LQ WITH(NOLOCK) ON PRE.IDKATIOS=LQ.IDKATIOS AND PE.IDDIARIO=LQ.IDDIARIO AND LQ.CONCEPTO='INTERES'
LEFT JOIN #SALDOSLIQUIDACION LQ2 WITH(NOLOCK) ON PRE.IDKATIOS=LQ2.IDKATIOS AND PE.IDDIARIO=LQ2.IDDIARIO AND LQ2.CONCEPTO='INTFINAL'
WHERE PRE.IDKATIOS=@IDKATIOS 
AND PRE.PRODUCTO NOT IN ('Venta Cuota Creciente','Venta de Flujos')
AND (CASE WHEN @TConsulta='FECHA_EFECTIVA' THEN CAST(DRO.FECHAEFECTIVA AS DATE) WHEN @TConsulta='FECHA_APLICACION' THEN CAST(DRO.FECHADIA AS DATE) END) BETWEEN @FECHAINICIAL AND @FECHAFINAL
GROUP BY PRE.IDKATIOS,DRO.IDDIARIO,LQ.CONDONACION,LQ.VALOR,LQ.IDLIQUIDACION,LQ2.VALOR,LQ2.CONDONACION

INSERT INTO #IVENCIDO
SELECT 
PE.Idkatios IDKATIOS
,PE.IdProducto IDPRESTAMO
,PE.IdDiario IDDIARIO
,ISNULL(SUM(PDKMORA.VALOR),0) KPAGADOCUOTA
FROM #INTERESPAGADO INP WITH(NOLOCK)
INNER JOIN PRSTMSENC PE WITH(NOLOCK) ON INP.IDKATIOS=PE.Idkatios AND INP.IDDIARIO=PE.IdDiario
INNER JOIN PrstmsDetalle PDDM WITH(NOLOCK) ON PE.Idkatios=PDDM.IDKATIOS AND PE.IdProducto=PDDM.IDPRESTAMO AND PE.IdDiario=PDDM.IDDIARIO AND PE.IdEncabezado=PDDM.IDENCABEZADO AND PDDM.NOMBRECUENTA='DIASMORA' AND PDDM.VALOR>0
LEFT JOIN PrstmsDetalle PDKMORA WITH(NOLOCK) ON PE.Idkatios=PDKMORA.IDKATIOS AND PE.IdProducto=PDKMORA.IDPRESTAMO AND PDDM.IdDiario=PDKMORA.IDDIARIO AND PDDM.IdEncabezado=PDKMORA.IDENCABEZADO AND PDKMORA.NOMBRECUENTA IN ('IPAGADO','IntFinales')
WHERE PE.IDKATIOS=@IDKATIOS 
GROUP BY PE.Idkatios,PE.IdProducto,PE.IdDiario

INSERT INTO #IFACTURADO
SELECT 
PE.Idkatios IDKATIOS
,PE.IdProducto IDPRESTAMO
,PE.IdDiario IDDIARIO
,ISNULL(SUM(PDKMORA.VALOR),0) KPAGADOCUOTA
FROM #INTERESPAGADO INP WITH(NOLOCK)
INNER JOIN PRSTMSENC PE WITH(NOLOCK) ON INP.IDKATIOS=PE.Idkatios AND INP.IDDIARIO=PE.IdDiario
INNER JOIN PrstmsDetalle PDDM WITH(NOLOCK) ON PE.Idkatios=PDDM.IDKATIOS AND PE.IdProducto=PDDM.IDPRESTAMO AND PE.IdDiario=PDDM.IDDIARIO AND PE.IdEncabezado=PDDM.IDENCABEZADO AND PDDM.NOMBRECUENTA='DIASMORA' AND PDDM.VALOR<=0
LEFT JOIN PrstmsDetalle PDKMORA WITH(NOLOCK) ON PE.Idkatios=PDKMORA.IDKATIOS AND PE.IdProducto=PDKMORA.IDPRESTAMO AND PDDM.IdDiario=PDKMORA.IDDIARIO AND PDDM.IdEncabezado=PDKMORA.IDENCABEZADO AND PDKMORA.NOMBRECUENTA IN ('IPAGADO','IntFinales')
WHERE PE.IDKATIOS=@IDKATIOS 
GROUP BY PE.Idkatios,PE.IdProducto,PE.IdDiario

INSERT INTO #SEGUROPAGADO
SELECT
PRE.IDKATIOS
,DRO.IDDIARIO
,CASE WHEN LQ.IDLIQUIDACION IS NULL THEN SUM(PD.VALOR) ELSE ISNULL(LQ.VALOR,0)+ ISNULL(LQ2.VALOR,0)-ISNULL(LQ.CONDONACION,0)-ISNULL(LQ2.CONDONACION,0) END
,CASE WHEN LQ.IDLIQUIDACION IS NULL THEN 0 ELSE ISNULL(LQ.CONDONACION,0)-ISNULL(LQ2.CONDONACION,0) END
FROM PRSTMS PRE WITH(NOLOCK)
INNER JOIN PRSTMSENC PE WITH(NOLOCK) ON PRE.IDKATIOS=PE.IDKATIOS AND PRE.IDPRESTAMO=PE.IDPRODUCTO AND PE.IDTRX IN ('5001', '5002', '5003','5013','5014','5015','5021') AND PE.REFERENCIA NOT LIKE '%RV%' AND PE.REFERENCIA <>'Adicion de observacion de cobranza'
INNER JOIN DIARIO DRO WITH(NOLOCK) ON PRE.IDKATIOS=DRO.IDKATIOS AND PE.IDDIARIO=DRO.IDDIARIO AND DRO.TIPOTRX<>'RV'
INNER JOIN PRSTMSDETALLE PD WITH(NOLOCK) ON PRE.IDKATIOS=PD.IDKATIOS AND PE.IDDIARIO=PD.IDDIARIO AND PE.IDENCABEZADO=PD.IDENCABEZADO AND PD.NOMBRECUENTA IN ('SPAGADO')
LEFT JOIN #SALDOSLIQUIDACION LQ WITH(NOLOCK) ON PRE.IDKATIOS=LQ.IDKATIOS AND PE.IDDIARIO=LQ.IDDIARIO AND LQ.CONCEPTO='SEGURO'
LEFT JOIN #SALDOSLIQUIDACION LQ2 WITH(NOLOCK) ON PRE.IDKATIOS=LQ2.IDKATIOS AND PE.IDDIARIO=LQ2.IDDIARIO AND LQ2.CONCEPTO='SEGFINAL'
WHERE PRE.IDKATIOS=@IDKATIOS 
AND PRE.PRODUCTO NOT IN ('Venta Cuota Creciente','Venta de Flujos')
AND (CASE WHEN @TConsulta='FECHA_EFECTIVA' THEN CAST(DRO.FECHAEFECTIVA AS DATE) WHEN @TConsulta='FECHA_APLICACION' THEN CAST(DRO.FECHADIA AS DATE) END) BETWEEN @FECHAINICIAL AND @FECHAFINAL
GROUP BY PRE.IDKATIOS,DRO.IDDIARIO,LQ.CONDONACION,LQ.VALOR,LQ.IDLIQUIDACION,LQ2.VALOR,LQ2.CONDONACION

INSERT INTO #GPSPAGADO
SELECT
PRE.IDKATIOS
,DRO.IDDIARIO
,CASE WHEN LQ.IDLIQUIDACION IS NULL THEN SUM(PD.VALOR) ELSE ISNULL(LQ.VALOR,0)+ISNULL(LQ2.VALOR,0)-ISNULL(LQ.CONDONACION,0)-ISNULL(LQ2.CONDONACION,0) END
,CASE WHEN LQ.IDLIQUIDACION IS NULL THEN 0 ELSE ISNULL(LQ.CONDONACION,0)-ISNULL(LQ2.CONDONACION,0) END
FROM PRSTMS PRE WITH(NOLOCK)
INNER JOIN PRSTMSENC PE WITH(NOLOCK) ON PRE.IDKATIOS=PE.IDKATIOS AND PRE.IDPRESTAMO=PE.IDPRODUCTO AND PE.IDTRX IN ('5001','5002', '5003','5013','5014','5015','5021') AND PE.REFERENCIA NOT LIKE '%RV%' AND PE.REFERENCIA <>'Adicion de observacion de cobranza'
INNER JOIN DIARIO DRO WITH(NOLOCK) ON PRE.IDKATIOS=DRO.IDKATIOS AND PE.IDDIARIO=DRO.IDDIARIO AND DRO.TIPOTRX<>'RV'
INNER JOIN PRSTMSDETALLE PD WITH(NOLOCK) ON PRE.IDKATIOS=PD.IDKATIOS AND PE.IDDIARIO=PD.IDDIARIO AND PE.IDENCABEZADO=PD.IDENCABEZADO AND PD.NOMBRECUENTA IN ('GPSPAGADO')
LEFT JOIN #SALDOSLIQUIDACION LQ WITH(NOLOCK) ON PRE.IDKATIOS=LQ.IDKATIOS AND PE.IDDIARIO=LQ.IDDIARIO AND LQ.CONCEPTO='GPSPAGADO'
LEFT JOIN #SALDOSLIQUIDACION LQ2 WITH(NOLOCK) ON PRE.IDKATIOS=LQ2.IDKATIOS AND PE.IDDIARIO=LQ2.IDDIARIO AND LQ2.CONCEPTO='GPSPAGADO'
WHERE PRE.IDKATIOS=@IDKATIOS 
AND PRE.PRODUCTO NOT IN ('Venta Cuota Creciente','Venta de Flujos')
AND (CASE WHEN @TConsulta='FECHA_EFECTIVA' THEN CAST(DRO.FECHAEFECTIVA AS DATE) WHEN @TConsulta='FECHA_APLICACION' THEN CAST(DRO.FECHADIA AS DATE) END) BETWEEN @FECHAINICIAL AND @FECHAFINAL
GROUP BY PRE.IDKATIOS,DRO.IDDIARIO,LQ.CONDONACION,LQ.VALOR,LQ.IDLIQUIDACION,LQ2.VALOR,LQ2.CONDONACION

INSERT INTO #MORAPAGADO
SELECT
PRE.IDKATIOS
,DRO.IDDIARIO
,CASE WHEN LQ.IDLIQUIDACION IS NULL THEN SUM(PD.VALOR) ELSE ISNULL(LQ.VALOR,0)-ISNULL(LQ.CONDONACION,0) END
,CASE WHEN LQ.IDLIQUIDACION IS NULL THEN 0 ELSE ISNULL(LQ.CONDONACION,0) END
FROM PRSTMS PRE WITH(NOLOCK)
INNER JOIN PRSTMSENC PE WITH(NOLOCK) ON PRE.IDKATIOS=PE.IDKATIOS AND PRE.IDPRESTAMO=PE.IDPRODUCTO AND PE.IDTRX IN ('5001', '5002', '5003','5013','5014','5015','5021') AND PE.REFERENCIA NOT LIKE '%RV%' AND PE.REFERENCIA <>'Adicion de observacion de cobranza'
INNER JOIN DIARIO DRO WITH(NOLOCK) ON PRE.IDKATIOS=DRO.IDKATIOS AND PE.IDDIARIO=DRO.IDDIARIO AND DRO.TIPOTRX<>'RV'
INNER JOIN PRSTMSDETALLE PD WITH(NOLOCK) ON PRE.IDKATIOS=PD.IDKATIOS AND PE.IDDIARIO=PD.IDDIARIO AND PE.IDENCABEZADO=PD.IDENCABEZADO AND PD.NOMBRECUENTA IN ('IMTOTAL','ISTOTAL')
LEFT JOIN #SALDOSLIQUIDACION LQ WITH(NOLOCK) ON PRE.IDKATIOS=LQ.IDKATIOS AND PE.IDDIARIO=LQ.IDDIARIO AND LQ.CONCEPTO='IMORA'
WHERE PRE.IDKATIOS=@IDKATIOS 
AND PRE.PRODUCTO NOT IN ('Venta Cuota Creciente','Venta de Flujos')
AND (CASE WHEN @TConsulta='FECHA_EFECTIVA' THEN CAST(DRO.FECHAEFECTIVA AS DATE) WHEN @TConsulta='FECHA_APLICACION' THEN CAST(DRO.FECHADIA AS DATE) END) BETWEEN @FECHAINICIAL AND @FECHAFINAL
GROUP BY PRE.IDKATIOS,DRO.IDDIARIO,LQ.CONDONACION,LQ.VALOR,LQ.IDLIQUIDACION

INSERT INTO #GACPAGADO
SELECT
PRE.IDKATIOS
,DRO.IDDIARIO
,CASE WHEN LQ.IDLIQUIDACION IS NULL THEN SUM(PD.VALOR) ELSE ISNULL(LQ.VALOR,0)-ISNULL(LQ.CONDONACION,0) END
,CASE WHEN LQ.IDLIQUIDACION IS NULL THEN 0 ELSE ISNULL(LQ.CONDONACION,0) END
FROM PRSTMS PRE WITH(NOLOCK)
INNER JOIN PRSTMSENC PE WITH(NOLOCK) ON PRE.IDKATIOS=PE.IDKATIOS AND PRE.IDPRESTAMO=PE.IDPRODUCTO AND PE.IDTRX IN ('5001', '5002', '5003','5013','5014','5015','5021') AND PE.REFERENCIA NOT LIKE '%RV%' AND PE.REFERENCIA <>'Adicion de observacion de cobranza'
INNER JOIN DIARIO DRO WITH(NOLOCK) ON PRE.IDKATIOS=DRO.IDKATIOS AND PE.IDDIARIO=DRO.IDDIARIO AND DRO.TIPOTRX<>'RV'
INNER JOIN PRSTMSDETALLE PD WITH(NOLOCK) ON PRE.IDKATIOS=PD.IDKATIOS AND PE.IDDIARIO=PD.IDDIARIO AND PE.IDENCABEZADO=PD.IDENCABEZADO AND PD.NOMBRECUENTA IN ('RTPAGADO','GCPAGADO')
LEFT JOIN #SALDOSLIQUIDACION LQ WITH(NOLOCK) ON PRE.IDKATIOS=LQ.IDKATIOS AND PE.IDDIARIO=LQ.IDDIARIO AND LQ.CONCEPTO='GAC'
WHERE PRE.IDKATIOS=@IDKATIOS 
AND PRE.PRODUCTO NOT IN ('Venta Cuota Creciente','Venta de Flujos')
AND (CASE WHEN @TConsulta='FECHA_EFECTIVA' THEN CAST(DRO.FECHAEFECTIVA AS DATE) WHEN @TConsulta='FECHA_APLICACION' THEN CAST(DRO.FECHADIA AS DATE) END) BETWEEN @FECHAINICIAL AND @FECHAFINAL
GROUP BY PRE.IDKATIOS,DRO.IDDIARIO,LQ.CONDONACION,LQ.VALOR,LQ.IDLIQUIDACION

INSERT INTO #IVAGACPAGADO
SELECT
PRE.IDKATIOS
,DRO.IDDIARIO
,CASE WHEN LQ.IDLIQUIDACION IS NULL THEN SUM(PD.VALOR) ELSE ISNULL(LQ.VALOR,0)-ISNULL(LQ.CONDONACION,0) END
,CASE WHEN LQ.IDLIQUIDACION IS NULL THEN 0 ELSE ISNULL(LQ.CONDONACION,0) END
FROM PRSTMS PRE WITH(NOLOCK)
INNER JOIN PRSTMSENC PE WITH(NOLOCK) ON PRE.IDKATIOS=PE.IDKATIOS AND PRE.IDPRESTAMO=PE.IDPRODUCTO AND PE.IDTRX IN ('5001', '5002', '5003','5013','5014','5015','5021') AND PE.REFERENCIA NOT LIKE '%RV%' AND PE.REFERENCIA <>'Adicion de observacion de cobranza'
INNER JOIN DIARIO DRO WITH(NOLOCK) ON PRE.IDKATIOS=DRO.IDKATIOS AND PE.IDDIARIO=DRO.IDDIARIO AND DRO.TIPOTRX<>'RV'
INNER JOIN PRSTMSDETALLE PD WITH(NOLOCK) ON PRE.IDKATIOS=PD.IDKATIOS AND PE.IDDIARIO=PD.IDDIARIO AND PE.IDENCABEZADO=PD.IDENCABEZADO AND PD.NOMBRECUENTA IN ('IGPAGADO')
LEFT JOIN #SALDOSLIQUIDACION LQ WITH(NOLOCK) ON PRE.IDKATIOS=LQ.IDKATIOS AND PE.IDDIARIO=LQ.IDDIARIO AND LQ.CONCEPTO='IVAGAC'
WHERE PRE.IDKATIOS=@IDKATIOS 
AND PRE.PRODUCTO NOT IN ('Venta Cuota Creciente','Venta de Flujos')
AND (CASE WHEN @TConsulta='FECHA_EFECTIVA' THEN CAST(DRO.FECHAEFECTIVA AS DATE) WHEN @TConsulta='FECHA_APLICACION' THEN CAST(DRO.FECHADIA AS DATE) END) BETWEEN @FECHAINICIAL AND @FECHAFINAL
GROUP BY PRE.IDKATIOS,DRO.IDDIARIO,LQ.CONDONACION,LQ.VALOR,LQ.IDLIQUIDACION

INSERT INTO #CXCPGRACIA
SELECT
PRE.IDKATIOS
,DRO.IDDIARIO
,CASE WHEN LQ.IDLIQUIDACION IS NULL THEN SUM(PD.VALOR) ELSE ISNULL(LQ.VALOR,0)-ISNULL(LQ.CONDONACION,0) END
,CASE WHEN LQ.IDLIQUIDACION IS NULL THEN 0 ELSE ISNULL(LQ.CONDONACION,0) END
FROM PRSTMS PRE WITH(NOLOCK)
INNER JOIN PRSTMSENC PE WITH(NOLOCK) ON PRE.IDKATIOS=PE.IDKATIOS AND PRE.IDPRESTAMO=PE.IDPRODUCTO AND PE.IDTRX IN ('5001', '5002', '5003','5013','5014','5015','5021') AND PE.REFERENCIA NOT LIKE '%RV%' AND PE.REFERENCIA <>'Adicion de observacion de cobranza'
INNER JOIN DIARIO DRO WITH(NOLOCK) ON PRE.IDKATIOS=DRO.IDKATIOS AND PE.IDDIARIO=DRO.IDDIARIO AND DRO.TIPOTRX<>'RV'
INNER JOIN PRSTMSDETALLE PD WITH(NOLOCK) ON PRE.IDKATIOS=PD.IDKATIOS AND PE.IDDIARIO=PD.IDDIARIO AND PE.IDENCABEZADO=PD.IDENCABEZADO AND PD.NOMBRECUENTA IN ('PGRACIA','PGPAGADO')
LEFT JOIN #SALDOSLIQUIDACION LQ WITH(NOLOCK) ON PRE.IDKATIOS=LQ.IDKATIOS AND PE.IDDIARIO=LQ.IDDIARIO AND LQ.CONCEPTO='PGRACIA'
WHERE PRE.IDKATIOS=@IDKATIOS 
AND PRE.PRODUCTO NOT IN ('Venta Cuota Creciente','Venta de Flujos')
AND (CASE WHEN @TConsulta='FECHA_EFECTIVA' THEN CAST(DRO.FECHAEFECTIVA AS DATE) WHEN @TConsulta='FECHA_APLICACION' THEN CAST(DRO.FECHADIA AS DATE) END) BETWEEN @FECHAINICIAL AND @FECHAFINAL
GROUP BY PRE.IDKATIOS,DRO.IDDIARIO,LQ.CONDONACION,LQ.VALOR,LQ.IDLIQUIDACION

INSERT INTO #CXCCGPS
SELECT
PRE.IDKATIOS
,DRO.IDDIARIO
,CASE WHEN LQ.IDLIQUIDACION IS NULL THEN SUM(PD.VALOR) ELSE ISNULL(LQ.VALOR,0)-ISNULL(LQ.CONDONACION,0) END
,CASE WHEN LQ.IDLIQUIDACION IS NULL THEN 0 ELSE ISNULL(LQ.CONDONACION,0) END
FROM PRSTMS PRE WITH(NOLOCK)
INNER JOIN PRSTMSENC PE WITH(NOLOCK) ON PRE.IDKATIOS=PE.IDKATIOS AND PRE.IDPRESTAMO=PE.IDPRODUCTO AND PE.IDTRX IN ('5001','5002', '5003','5013','5014','5015','5021') AND PE.REFERENCIA NOT LIKE '%RV%' AND PE.REFERENCIA <>'Adicion de observacion de cobranza'
INNER JOIN DIARIO DRO WITH(NOLOCK) ON PRE.IDKATIOS=DRO.IDKATIOS AND PE.IDDIARIO=DRO.IDDIARIO AND DRO.TIPOTRX<>'RV'
INNER JOIN PRSTMSDETALLE PD WITH(NOLOCK) ON PRE.IDKATIOS=PD.IDKATIOS AND PE.IDDIARIO=PD.IDDIARIO AND PE.IDENCABEZADO=PD.IDENCABEZADO AND PD.NOMBRECUENTA IN ('CXCCGPAGADO')
LEFT JOIN #SALDOSLIQUIDACION LQ WITH(NOLOCK) ON PRE.IDKATIOS=LQ.IDKATIOS AND PE.IDDIARIO=LQ.IDDIARIO AND LQ.CONCEPTO='CXCCGPAGADO'
WHERE PRE.IDKATIOS=@IDKATIOS 
AND PRE.PRODUCTO NOT IN ('Venta Cuota Creciente','Venta de Flujos')
AND (CASE WHEN @TConsulta='FECHA_EFECTIVA' THEN CAST(DRO.FECHAEFECTIVA AS DATE) WHEN @TConsulta='FECHA_APLICACION' THEN CAST(DRO.FECHADIA AS DATE) END) BETWEEN @FECHAINICIAL AND @FECHAFINAL
GROUP BY PRE.IDKATIOS,DRO.IDDIARIO,LQ.CONDONACION,LQ.VALOR,LQ.IDLIQUIDACION

INSERT INTO #SALDOAFAVORPAGADO
SELECT
PRE.IDKATIOS
,DRO.IDDIARIO
,CASE WHEN LQ.IDLIQUIDACION IS NULL THEN -SUM(PD.CREDITO)+SUM(PD.DEBITO) ELSE ISNULL(LQ.VALOR,0)-ISNULL(LQ.CONDONACION,0) END
,CASE WHEN LQ.IDLIQUIDACION IS NULL THEN 0 ELSE ISNULL(LQ.CONDONACION,0) END
FROM PRSTMS PRE WITH(NOLOCK)
INNER JOIN PRSTMSENC PE WITH(NOLOCK) ON PRE.IDKATIOS=PE.IDKATIOS AND PRE.IDPRESTAMO=PE.IDPRODUCTO AND PE.IDTRX IN ('5001', '5002', '5003','5013','5014','5015','5021') AND PE.REFERENCIA NOT LIKE '%RV%' AND PE.REFERENCIA <>'Adicion de observacion de cobranza'
INNER JOIN DIARIO DRO WITH(NOLOCK) ON PRE.IDKATIOS=DRO.IDKATIOS AND PE.IDDIARIO=DRO.IDDIARIO AND DRO.TIPOTRX<>'RV'
INNER JOIN PRSTMSDETALLE PD WITH(NOLOCK) ON PRE.IDKATIOS=PD.IDKATIOS AND PE.IDDIARIO=PD.IDDIARIO AND PE.IDENCABEZADO=PD.IDENCABEZADO AND PD.NOMBRECUENTA IN ('SaldoAFavor')
LEFT JOIN #SALDOSLIQUIDACION LQ WITH(NOLOCK) ON PRE.IDKATIOS=LQ.IDKATIOS AND PE.IDDIARIO=LQ.IDDIARIO AND LQ.CONCEPTO='SF'
WHERE PRE.IDKATIOS=@IDKATIOS 
AND PRE.PRODUCTO NOT IN ('Venta Cuota Creciente','Venta de Flujos')
AND (CASE WHEN @TConsulta='FECHA_EFECTIVA' THEN CAST(DRO.FECHAEFECTIVA AS DATE) WHEN @TConsulta='FECHA_APLICACION' THEN CAST(DRO.FECHADIA AS DATE) END) BETWEEN @FECHAINICIAL AND @FECHAFINAL
GROUP BY PRE.IDKATIOS,DRO.IDDIARIO,LQ.CONDONACION,LQ.VALOR,LQ.IDLIQUIDACION

INSERT INTO #CXCRUNT
SELECT
PRE.IDKATIOS
,DRO.IDDIARIO
,CASE WHEN LQ.IDLIQUIDACION IS NULL THEN SUM(PD.VALOR) ELSE ISNULL(LQ.VALOR,0)-ISNULL(LQ.CONDONACION,0) END
,CASE WHEN LQ.IDLIQUIDACION IS NULL THEN 0 ELSE ISNULL(LQ.CONDONACION,0) END
FROM PRSTMS PRE WITH(NOLOCK)
INNER JOIN PRSTMSENC PE WITH(NOLOCK) ON PRE.IDKATIOS=PE.IDKATIOS AND PRE.IDPRESTAMO=PE.IDPRODUCTO AND PE.IDTRX IN ('5001', '5002', '5003','5013','5014','5015','5021') AND PE.REFERENCIA NOT LIKE '%RV%' AND PE.REFERENCIA <>'Adicion de observacion de cobranza'
INNER JOIN DIARIO DRO WITH(NOLOCK) ON PRE.IDKATIOS=DRO.IDKATIOS AND PE.IDDIARIO=DRO.IDDIARIO AND DRO.TIPOTRX<>'RV'
INNER JOIN PRSTMSDETALLE PD WITH(NOLOCK) ON PRE.IDKATIOS=PD.IDKATIOS AND PE.IDDIARIO=PD.IDDIARIO AND PE.IDENCABEZADO=PD.IDENCABEZADO AND PD.NOMBRECUENTA IN ('CXCRUPAGADO')
LEFT JOIN #SALDOSLIQUIDACION LQ WITH(NOLOCK) ON PRE.IDKATIOS=LQ.IDKATIOS AND PE.IDDIARIO=LQ.IDDIARIO AND LQ.CONCEPTO='CXC'
WHERE PRE.IDKATIOS=@IDKATIOS 
AND PRE.PRODUCTO NOT IN ('Venta Cuota Creciente','Venta de Flujos')
AND (CASE WHEN @TConsulta='FECHA_EFECTIVA' THEN CAST(DRO.FECHAEFECTIVA AS DATE) WHEN @TConsulta='FECHA_APLICACION' THEN CAST(DRO.FECHADIA AS DATE) END) BETWEEN @FECHAINICIAL AND @FECHAFINAL
GROUP BY PRE.IDKATIOS,DRO.IDDIARIO,LQ.CONDONACION,LQ.VALOR,LQ.IDLIQUIDACION

INSERT INTO #CXCGARANTIASM
SELECT
PRE.IDKATIOS
,DRO.IDDIARIO
,CASE WHEN LQ.IDLIQUIDACION IS NULL THEN SUM(PD.VALOR) ELSE ISNULL(LQ.VALOR,0)-ISNULL(LQ.CONDONACION,0) END
,CASE WHEN LQ.IDLIQUIDACION IS NULL THEN 0 ELSE ISNULL(LQ.CONDONACION,0) END
FROM PRSTMS PRE WITH(NOLOCK)
INNER JOIN PRSTMSENC PE WITH(NOLOCK) ON PRE.IDKATIOS=PE.IDKATIOS AND PRE.IDPRESTAMO=PE.IDPRODUCTO AND PE.IDTRX IN ('5001', '5002', '5003','5013','5014','5015','5021') AND PE.REFERENCIA NOT LIKE '%RV%' AND PE.REFERENCIA <>'Adicion de observacion de cobranza'
INNER JOIN DIARIO DRO WITH(NOLOCK) ON PRE.IDKATIOS=DRO.IDKATIOS AND PE.IDDIARIO=DRO.IDDIARIO AND DRO.TIPOTRX<>'RV'
INNER JOIN PRSTMSDETALLE PD WITH(NOLOCK) ON PRE.IDKATIOS=PD.IDKATIOS AND PE.IDDIARIO=PD.IDDIARIO AND PE.IDENCABEZADO=PD.IDENCABEZADO AND PD.NOMBRECUENTA IN ('CXCGAPAGADO')
LEFT JOIN #SALDOSLIQUIDACION LQ WITH(NOLOCK) ON PRE.IDKATIOS=LQ.IDKATIOS AND PE.IDDIARIO=LQ.IDDIARIO AND LQ.CONCEPTO='CXC'
WHERE PRE.IDKATIOS=@IDKATIOS 
AND PRE.PRODUCTO NOT IN ('Venta Cuota Creciente','Venta de Flujos')
AND (CASE WHEN @TConsulta='FECHA_EFECTIVA' THEN CAST(DRO.FECHAEFECTIVA AS DATE) WHEN @TConsulta='FECHA_APLICACION' THEN CAST(DRO.FECHADIA AS DATE) END) BETWEEN @FECHAINICIAL AND @FECHAFINAL
GROUP BY PRE.IDKATIOS,DRO.IDDIARIO,LQ.CONDONACION,LQ.VALOR,LQ.IDLIQUIDACION

INSERT INTO #CXCIVAGARANTIAS
SELECT
PRE.IDKATIOS
,DRO.IDDIARIO
,CASE WHEN LQ.IDLIQUIDACION IS NULL THEN SUM(PD.VALOR) ELSE ISNULL(LQ.VALOR,0)-ISNULL(LQ.CONDONACION,0) END
,CASE WHEN LQ.IDLIQUIDACION IS NULL THEN 0 ELSE ISNULL(LQ.CONDONACION,0) END
FROM PRSTMS PRE WITH(NOLOCK)
INNER JOIN PRSTMSENC PE WITH(NOLOCK) ON PRE.IDKATIOS=PE.IDKATIOS AND PRE.IDPRESTAMO=PE.IDPRODUCTO AND PE.IDTRX IN ('5001', '5002', '5003','5013','5014','5015','5021') AND PE.REFERENCIA NOT LIKE '%RV%' AND PE.REFERENCIA <>'Adicion de observacion de cobranza'
INNER JOIN DIARIO DRO WITH(NOLOCK) ON PRE.IDKATIOS=DRO.IDKATIOS AND PE.IDDIARIO=DRO.IDDIARIO AND DRO.TIPOTRX<>'RV'
INNER JOIN PRSTMSDETALLE PD WITH(NOLOCK) ON PRE.IDKATIOS=PD.IDKATIOS AND PE.IDDIARIO=PD.IDDIARIO AND PE.IDENCABEZADO=PD.IDENCABEZADO AND PD.NOMBRECUENTA IN ('CXCIVPAGADO')
LEFT JOIN #SALDOSLIQUIDACION LQ WITH(NOLOCK) ON PRE.IDKATIOS=LQ.IDKATIOS AND PE.IDDIARIO=LQ.IDDIARIO AND LQ.CONCEPTO='CXC'
WHERE PRE.IDKATIOS=@IDKATIOS 
AND PRE.PRODUCTO NOT IN ('Venta Cuota Creciente','Venta de Flujos')
AND (CASE WHEN @TConsulta='FECHA_EFECTIVA' THEN CAST(DRO.FECHAEFECTIVA AS DATE) WHEN @TConsulta='FECHA_APLICACION' THEN CAST(DRO.FECHADIA AS DATE) END) BETWEEN @FECHAINICIAL AND @FECHAFINAL
GROUP BY PRE.IDKATIOS,DRO.IDDIARIO,LQ.CONDONACION,LQ.VALOR,LQ.IDLIQUIDACION

INSERT INTO #CXCIINICIALES
SELECT
PRE.IDKATIOS
,DRO.IDDIARIO
,CASE WHEN LQ.IDLIQUIDACION IS NULL THEN SUM(PD.VALOR) ELSE ISNULL(LQ.VALOR,0)-ISNULL(LQ.CONDONACION,0) END
,CASE WHEN LQ.IDLIQUIDACION IS NULL THEN 0 ELSE ISNULL(LQ.CONDONACION,0) END
FROM PRSTMS PRE WITH(NOLOCK)
INNER JOIN PRSTMSENC PE WITH(NOLOCK) ON PRE.IDKATIOS=PE.IDKATIOS AND PRE.IDPRESTAMO=PE.IDPRODUCTO AND PE.IDTRX IN ('5001', '5002', '5003','5013','5014','5015','5021') AND PE.REFERENCIA NOT LIKE '%RV%' AND PE.REFERENCIA <>'Adicion de observacion de cobranza'
INNER JOIN DIARIO DRO WITH(NOLOCK) ON PRE.IDKATIOS=DRO.IDKATIOS AND PE.IDDIARIO=DRO.IDDIARIO AND DRO.TIPOTRX<>'RV'
INNER JOIN PRSTMSDETALLE PD WITH(NOLOCK) ON PRE.IDKATIOS=PD.IDKATIOS AND PE.IDDIARIO=PD.IDDIARIO AND PE.IDENCABEZADO=PD.IDENCABEZADO AND PD.NOMBRECUENTA IN ('CXCINPAGADO')
LEFT JOIN #SALDOSLIQUIDACION LQ WITH(NOLOCK) ON PRE.IDKATIOS=LQ.IDKATIOS AND PE.IDDIARIO=LQ.IDDIARIO AND LQ.CONCEPTO='CXC'
WHERE PRE.IDKATIOS=@IDKATIOS 
AND PRE.PRODUCTO NOT IN ('Venta Cuota Creciente','Venta de Flujos')
AND (CASE WHEN @TConsulta='FECHA_EFECTIVA' THEN CAST(DRO.FECHAEFECTIVA AS DATE) WHEN @TConsulta='FECHA_APLICACION' THEN CAST(DRO.FECHADIA AS DATE) END) BETWEEN @FECHAINICIAL AND @FECHAFINAL
GROUP BY PRE.IDKATIOS,DRO.IDDIARIO,LQ.CONDONACION,LQ.VALOR,LQ.IDLIQUIDACION

INSERT INTO #CAPITALMORA
SELECT
PRE.IDKATIOS
,DRO.IDDIARIO
,SUM(PD.VALOR)
FROM Prstms PRE WITH(NOLOCK)
INNER JOIN PRSTMSENC PE WITH(NOLOCK) ON PRE.IDKATIOS=PE.IDKATIOS AND PRE.IDPRESTAMO=PE.IDPRODUCTO AND PE.IDTRX IN ('5001', '5002', '5003','5013','5014','5015','5021') AND PE.REFERENCIA NOT LIKE '%RV%' AND PE.REFERENCIA <>'Adicion de observacion de cobranza'
INNER JOIN DIARIO DRO WITH(NOLOCK) ON PRE.IDKATIOS=DRO.IDKATIOS AND PE.IDDIARIO=DRO.IDDIARIO AND DRO.TIPOTRX<>'RV'
INNER JOIN PRSTMSDETALLE PD WITH(NOLOCK) ON PRE.IDKATIOS=PD.IDKATIOS AND PE.IDDIARIO=PD.IDDIARIO AND PE.IDENCABEZADO=PD.IDENCABEZADO AND PD.NOMBRECUENTA IN ('KPAGADO','IPAGADO','SPAGADO')
INNER JOIN PRSTMSDETALLE PD2 WITH(NOLOCK) ON PRE.IDKATIOS=PD2.IDKATIOS AND PE.IDDIARIO=PD2.IDDIARIO AND PE.IDENCABEZADO=PD2.IDENCABEZADO AND PD2.NOMBRECUENTA IN ('DIASMORA') AND PD2.VALOR>'0'
WHERE PRE.IDKATIOS=@IDKATIOS 
AND PRE.PRODUCTO NOT IN ('Venta Cuota Creciente','Venta de Flujos')
AND (CASE WHEN @TConsulta='FECHA_EFECTIVA' THEN CAST(DRO.FECHAEFECTIVA AS DATE) WHEN @TConsulta='FECHA_APLICACION' THEN CAST(DRO.FECHADIA AS DATE) END) BETWEEN @FECHAINICIAL AND @FECHAFINAL 
AND DRO.FECHAEFECTIVA>DATEADD(M,PE.CUOTA,PRE.FECHAINICIAL)
GROUP BY PRE.IDKATIOS,DRO.IDDIARIO

INSERT INTO #EDADMORA
SELECT
PRE.IDKATIOS
,DRO.IDDIARIO
,DATEDIFF(D,DATEADD(M,PE.CUOTA,PRE.FECHAINICIAL),DRO.FECHAEFECTIVA)
,PD.VALOR
,CASE
WHEN DATEDIFF(D,DATEADD(M,PE.CUOTA,PRE.FECHAINICIAL),DRO.FECHAEFECTIVA) <=0 THEN 'AL DIA' 
WHEN DATEDIFF(D,DATEADD(M,PE.CUOTA,PRE.FECHAINICIAL),DRO.FECHAEFECTIVA) >=1 AND DATEDIFF(D,DATEADD(M,PE.CUOTA,PRE.FECHAINICIAL),DRO.FECHAEFECTIVA) <=29 THEN 'NORMAL' 
WHEN DATEDIFF(D,DATEADD(M,PE.CUOTA,PRE.FECHAINICIAL),DRO.FECHAEFECTIVA) >=30 AND DATEDIFF(D,DATEADD(M,PE.CUOTA,PRE.FECHAINICIAL),DRO.FECHAEFECTIVA) <=59 THEN 'MORA 30'
WHEN DATEDIFF(D,DATEADD(M,PE.CUOTA,PRE.FECHAINICIAL),DRO.FECHAEFECTIVA) >=60 AND DATEDIFF(D,DATEADD(M,PE.CUOTA,PRE.FECHAINICIAL),DRO.FECHAEFECTIVA) <=89 THEN 'MORA 60'
WHEN DATEDIFF(D,DATEADD(M,PE.CUOTA,PRE.FECHAINICIAL),DRO.FECHAEFECTIVA) >=90 AND DATEDIFF(D,DATEADD(M,PE.CUOTA,PRE.FECHAINICIAL),DRO.FECHAEFECTIVA) <=119 THEN 'MORA 90'
WHEN DATEDIFF(D,DATEADD(M,PE.CUOTA,PRE.FECHAINICIAL),DRO.FECHAEFECTIVA) >=120 AND DATEDIFF(D,DATEADD(M,PE.CUOTA,PRE.FECHAINICIAL),DRO.FECHAEFECTIVA) <=149 THEN 'MORA 120'
WHEN DATEDIFF(D,DATEADD(M,PE.CUOTA,PRE.FECHAINICIAL),DRO.FECHAEFECTIVA) >=150 AND DATEDIFF(D,DATEADD(M,PE.CUOTA,PRE.FECHAINICIAL),DRO.FECHAEFECTIVA) <=179 THEN 'MORA 150'
WHEN DATEDIFF(D,DATEADD(M,PE.CUOTA,PRE.FECHAINICIAL),DRO.FECHAEFECTIVA) >=180 AND DATEDIFF(D,DATEADD(M,PE.CUOTA,PRE.FECHAINICIAL),DRO.FECHAEFECTIVA) <=209 THEN 'MORA 180'
WHEN DATEDIFF(D,DATEADD(M,PE.CUOTA,PRE.FECHAINICIAL),DRO.FECHAEFECTIVA) >=210 AND DATEDIFF(D,DATEADD(M,PE.CUOTA,PRE.FECHAINICIAL),DRO.FECHAEFECTIVA) <=239 THEN 'MORA 210'
WHEN DATEDIFF(D,DATEADD(M,PE.CUOTA,PRE.FECHAINICIAL),DRO.FECHAEFECTIVA) >=240 AND DATEDIFF(D,DATEADD(M,PE.CUOTA,PRE.FECHAINICIAL),DRO.FECHAEFECTIVA) <=269 THEN 'MORA 240'
WHEN DATEDIFF(D,DATEADD(M,PE.CUOTA,PRE.FECHAINICIAL),DRO.FECHAEFECTIVA) >=270 AND DATEDIFF(D,DATEADD(M,PE.CUOTA,PRE.FECHAINICIAL),DRO.FECHAEFECTIVA) <=299 THEN 'MORA 270'
WHEN DATEDIFF(D,DATEADD(M,PE.CUOTA,PRE.FECHAINICIAL),DRO.FECHAEFECTIVA) >=300 AND DATEDIFF(D,DATEADD(M,PE.CUOTA,PRE.FECHAINICIAL),DRO.FECHAEFECTIVA) <=329 THEN 'MORA 300'
WHEN DATEDIFF(D,DATEADD(M,PE.CUOTA,PRE.FECHAINICIAL),DRO.FECHAEFECTIVA) >=330 AND DATEDIFF(D,DATEADD(M,PE.CUOTA,PRE.FECHAINICIAL),DRO.FECHAEFECTIVA) <=359 THEN 'MORA 330'
WHEN DATEDIFF(D,DATEADD(M,PE.CUOTA,PRE.FECHAINICIAL),DRO.FECHAEFECTIVA) >=360 AND DATEDIFF(D,DATEADD(M,PE.CUOTA,PRE.FECHAINICIAL),DRO.FECHAEFECTIVA) <=539 THEN 'MORA 360'
WHEN DATEDIFF(D,DATEADD(M,PE.CUOTA,PRE.FECHAINICIAL),DRO.FECHAEFECTIVA) >=540 AND DATEDIFF(D,DATEADD(M,PE.CUOTA,PRE.FECHAINICIAL),DRO.FECHAEFECTIVA) <=729 THEN 'MORA 540'
WHEN DATEDIFF(D,DATEADD(M,PE.CUOTA,PRE.FECHAINICIAL),DRO.FECHAEFECTIVA) >=730 THEN 'MORA 730'
END AS 'EDAD_MORA'
FROM Prstms PRE WITH(NOLOCK)
INNER JOIN PRSTMSDETALLE PD WITH(NOLOCK) ON PRE.IDKATIOS=PD.IDKATIOS AND PRE.IDPRESTAMO=PD.IDPRESTAMO AND PD.NOMBRECUENTA IN ('DIASMORA') and PD.IDencabezado='1'
INNER JOIN DIARIO DRO WITH(NOLOCK) ON PRE.IDKATIOS=DRO.IDKATIOS AND PD.IDDIARIO=DRO.IDDIARIO AND DRO.TIPOTRX<>'RV'
INNER JOIN PRSTMSENC PE WITH(NOLOCK) ON PRE.IDKATIOS=PE.IDKATIOS AND PD.IDDIARIO=PE.IDDIARIO AND PD.IDENCABEZADO=PE.IDENCABEZADO AND PE.IDTRX IN ('5001', '5002', '5003', '5015','5013','5014','5021') AND PE.REFERENCIA NOT LIKE '%RV%' AND PE.REFERENCIA <>'Adicion de observacion de cobranza' 
WHERE PRE.IDKATIOS=@IDKATIOS 
AND (CASE WHEN @TConsulta='FECHA_EFECTIVA' THEN CAST(DRO.FECHAEFECTIVA AS DATE) WHEN @TConsulta='FECHA_APLICACION' THEN CAST(DRO.FECHADIA AS DATE) END) BETWEEN @FECHAINICIAL AND @FECHAFINAL
AND PRE.PRODUCTO NOT IN ('Venta Cuota Creciente','Venta de Flujos')
GROUP BY PRE.IDKATIOS,DRO.IDDIARIO, PD.VALOR,PE.CUOTA,PRE.FECHAINICIAL,DRO.FECHAEFECTIVA

INSERT INTO #AplicacionPagosTemporal
SELECT
DRO.FECHADIA AS 'FECHA_APLICACION'
,PRE.CTIVO AS 'CREDITO'
,PER.NDOC AS 'DOCUMENTO'
,PER.NOMBRES AS 'TITULAR'
,CASE 
WHEN DRO.Dato2='APL_SALDOS' THEN 'APLICACION SALDOS' 
WHEN DRO.Dato2='APLSALDOS' THEN 'APLICACION SALDOS' 
WHEN LQ.IDDIARIO IS NOT NULL THEN ISNULL((SELECT TOP 1 NOMBRECUENTA FROM CONTADETALLE WITH(NOLOCK) WHERE IDKATIOS=PRE.IDKATIOS AND IDDIARIO=PE.IDDIARIO AND Memo='RECAUDO' ),'AJUSTE')
ELSE ISNULL((SELECT TOP 1 NOMBRECUENTA FROM CONTADETALLE WITH(NOLOCK) WHERE IDKATIOS=PRE.IDKATIOS AND IDDIARIO=PE.IDDIARIO AND (CUENTACONTABLE LIKE '238095%' OR CUENTACONTABLE LIKE '%189520%' OR CUENTACONTABLE LIKE '%519595%' OR CUENTACONTABLE LIKE '%111005%' OR CUENTACONTABLE LIKE '%112005%' OR CUENTACONTABLE LIKE '%280505%'  OR CUENTACONTABLE LIKE '%839595%' OR CUENTACONTABLE LIKE '%110505%' ) ),'AJUSTE') 
END AS 'CUENTA_RECAUDO' 
,DRO.FECHAEFECTIVA AS 'FECHA_PAGO'
,CASE WHEN ISNULL(IIF(RTRIM(LTRIM(TX.DESCRIPCION))='SCONTRA','PAGAR',TX.DESCRIPCION),'')='SALDO A FAVOR' THEN 'CXP RENTEK' ELSE ISNULL(IIF(RTRIM(LTRIM(TX.DESCRIPCION))='SCONTRA','PAGAR',TX.DESCRIPCION),'') END AS 'TRANSACCION'
,ISNULL(DRO.VALOR,0) - ISNULL(PL.Condonacion,0) AS 'VALOR_PAGADO'
,ISNULL(CPAG.VALOR,0) AS 'KPAGADO'
,ISNULL(IPAG.VALOR,0) AS 'IPAGADO'
,ISNULL(SPAG.VALOR,0) AS 'SEGURO'
,ISNULL(MPAG.VALOR,0) AS 'MORA'
,ISNULL(GCPAG.VALOR,0) AS 'GASTOS_DE_COBRANZA' 
,ISNULL(IVGPAG.VALOR,0) AS 'IVAGAC' 
,ISNULL(CPG.VALOR,0) AS 'CXCPGRACIA'
,ISNULL(SAFPAG.VALOR,0) AS 'SAFAVOR'
,ISNULL(CRT.VALOR,0) AS 'RUNT' 
,ISNULL(CGM.VALOR,0) AS 'GARANTIAS_MOBILIARIAS' 
,ISNULL(CIGM.VALOR,0) AS 'IVA_GARANTIAS_MOBILIARIAS' 
,ISNULL(GPSP.VALOR,0) AS 'GPS_PAGADO'
,ISNULL(CIIN.VALOR,0) AS 'I_INICALES' 
,ISNULL(KPV.KPAGADOVENC,0) 'KFACTURADO_VENCIDO'
,ISNULL(KPNV.KPAGADONOVENC,0) 'KFACTURADO_NO_VENCIDO'
,ISNULL(CPAG.VALOR-ISNULL(KPV.KPAGADOVENC,0)-ISNULL(KPNV.KPAGADONOVENC,0),0) 'KNO_FACTURADO'
,ISNULL(CM.VALOR,0) AS 'CAPITAL_MORA'
,ISNULL(IVE.VALOR,0) AS 'IVENCIDO'
,ISNULL(IFA.VALOR,0) AS 'IFACTURADO'
,(SELECT SUBSTRING(ISNULL((SELECT DISTINCT ' - '+ CAST(convert(varchar(10),DATEADD(M,PD.CUOTA,PRE.FECHAINICIAL), 103) AS VARCHAR(MAX)) FROM PRSTMSENC AS PD WITH(NOLOCK) WHERE PD.IDKATIOS=PRE.IDKATIOS AND PD.IDDIARIO=PE.IDDIARIO FOR XML PATH('')),''),3, 255)) AS 'CUOTAS'
,ISNULL((SELECT TOP(1) PD.ESTADO FROM PRSTMSDETALLE PD WITH(NOLOCK) WHERE PD.IDKATIOS=PRE.IDKATIOS AND PD.IDPRESTAMO=PRE.IDPRESTAMO AND PD.IDDIARIO=DRO.IDDIARIO AND PD.NOMBRECUENTA='IdEstado' ),'ACTIVO') AS 'ESTADO' 
,PRE.SUBESTADO AS 'SUBESTADO'
,ISNULL(EM.EDADMORA,'AL DIA') AS 'EDAD_MORA'
,ISNULL(PRE.PRODUCTO,'') AS 'PRODUCTO'
,ISNULL(CE.CTIVO,'') AS 'CONSECUTIVO'
,ISNULL(DRO.Dato2,'') AS 'REFERENCIA'
,ISNULL(IFIN.VALOR,0) AS 'INT_FINALES'

FROM PRSTMS PRE WITH(NOLOCK)
INNER JOIN PRSTMSENC PE WITH(NOLOCK) ON PRE.IDKATIOS=PE.IDKATIOS AND PRE.IDPRESTAMO=PE.IDPRODUCTO AND PE.IDTRX IN ('5001', '5002', '5003', '5013','5014', '5015','5021','5016') AND PE.REFERENCIA NOT LIKE '%RV%' AND  PE.REFERENCIA NOT IN ('Adicion de observacion de cobranza', 'APLSALDOS') AND PE.IdEncabezado='1'
INNER JOIN DIARIO DRO WITH(NOLOCK) ON PRE.IDKATIOS=DRO.IDKATIOS AND PE.IDDIARIO=DRO.IDDIARIO AND DRO.TIPOTRX<>'RV'
INNER JOIN PERSONAS PER WITH(NOLOCK) ON PRE.IDKATIOS=PER.IDKATIOS AND PRE.NDOC=PER.NDOC
INNER JOIN TRX TX WITH(NOLOCK) ON PRE.IDKATIOS=TX.IDKATIOS AND PE.IDTRX=TX.IDTRX
LEFT JOIN #LIQUIDACION LQ WITH(NOLOCK) ON PRE.IDKATIOS=LQ.IDKATIOS AND DRO.IDDIARIO=LQ.IDDIARIO
LEFT JOIN PrstmsLiquidacion PL WITH(NOLOCK) ON PRE.IdKatios=PL.IdKatios AND PRE.IdPrestamo=PL.IdPrestamo AND LQ.IDLIQUIDACION=PL.IdLiquidacion
LEFT JOIN #CAPITALPAGADO CPAG WITH(NOLOCK) ON PRE.IDKATIOS=CPAG.IDKATIOS AND DRO.IDDIARIO=CPAG.IDDIARIO
LEFT JOIN #KPAGADOXCUOTAVENCIDA KPV WITH(NOLOCK) ON PRE.IdKatios=KPV.IDKATIOS AND PRE.IdPrestamo=KPV.IDPRESTAMO AND DRO.IDDIARIO=KPV.IDDIARIO
LEFT JOIN #KPAGADOXCUOTANOVENCIDA KPNV WITH(NOLOCK) ON PRE.IdKatios=KPNV.IDKATIOS AND PRE.IdPrestamo=KPNV.IDPRESTAMO AND DRO.IDDIARIO=KPNV.IDDIARIO
LEFT JOIN #INTERESPAGADO IPAG WITH(NOLOCK) ON PRE.IDKATIOS=IPAG.IDKATIOS AND DRO.IDDIARIO=IPAG.IDDIARIO
LEFT JOIN #INTFINALES IFIN WITH(NOLOCK) ON PRE.IDKATIOS=IFIN.IDKATIOS AND DRO.IDDIARIO=IFIN.IDDIARIO
LEFT JOIN #IVENCIDO IVE WITH(NOLOCK) ON PRE.IdKatios=IVE.IDKATIOS AND PRE.IdPrestamo=IVE.IDPRESTAMO AND DRO.IDDIARIO=IVE.IDDIARIO
LEFT JOIN #IFACTURADO IFA WITH(NOLOCK) ON PRE.IdKatios=IFA.IDKATIOS AND PRE.IdPrestamo=IFA.IDPRESTAMO AND DRO.IDDIARIO=IFA.IDDIARIO
LEFT JOIN #SEGUROPAGADO SPAG WITH(NOLOCK) ON PRE.IDKATIOS=SPAG.IDKATIOS AND DRO.IDDIARIO=SPAG.IDDIARIO
LEFT JOIN #MORAPAGADO MPAG WITH(NOLOCK) ON PRE.IDKATIOS=MPAG.IDKATIOS AND DRO.IDDIARIO=MPAG.IDDIARIO
LEFT JOIN #GACPAGADO GCPAG WITH(NOLOCK) ON PRE.IDKATIOS=GCPAG.IDKATIOS AND DRO.IDDIARIO=GCPAG.IDDIARIO
LEFT JOIN #IVAGACPAGADO IVGPAG WITH(NOLOCK) ON PRE.IDKATIOS=IVGPAG.IDKATIOS AND DRO.IDDIARIO=IVGPAG.IDDIARIO
LEFT JOIN #CXCPGRACIA CPG WITH(NOLOCK) ON PRE.IDKATIOS=CPG.IDKATIOS AND DRO.IDDIARIO=CPG.IDDIARIO
LEFT JOIN #SALDOAFAVORPAGADO SAFPAG WITH(NOLOCK) ON PRE.IDKATIOS=SAFPAG.IDKATIOS AND DRO.IDDIARIO=SAFPAG.IDDIARIO
LEFT JOIN #CXCRUNT CRT WITH(NOLOCK) ON PRE.IDKATIOS=CRT.IDKATIOS AND DRO.IDDIARIO=CRT.IDDIARIO
LEFT JOIN #CXCGARANTIASM CGM WITH(NOLOCK) ON PRE.IDKATIOS=CGM.IDKATIOS AND DRO.IDDIARIO=CGM.IDDIARIO
LEFT JOIN #CXCIVAGARANTIAS CIGM WITH(NOLOCK) ON PRE.IDKATIOS=CIGM.IDKATIOS AND DRO.IDDIARIO=CIGM.IDDIARIO
LEFT JOIN #CXCIINICIALES CIIN WITH(NOLOCK) ON PRE.IDKATIOS=CIIN.IDKATIOS AND DRO.IDDIARIO=CIIN.IDDIARIO
LEFT JOIN #CAPITALMORA CM ON PRE.IDKATIOS=CM.IDKATIOS AND DRO.IDDIARIO = CM.IDDIARIO
LEFT JOIN #EDADMORA EM ON PRE.IDKATIOS=EM.IDKATIOS AND DRO.IDDIARIO = EM.IDDIARIO 
LEFT JOIN #GPSPAGADO GPSP WITH(NOLOCK) ON PRE.IDKATIOS=GPSP.IDKATIOS AND DRO.IDDIARIO=GPSP.IDDIARIO
LEFT JOIN #CXCCGPS CXCGPS WITH(NOLOCK) ON PRE.IDKATIOS=CXCGPS.IDKATIOS AND DRO.IDDIARIO=CXCGPS.IDDIARIO
LEFT JOIN CONTAENC CE WITH(NOLOCK) ON PRE.IDKATIOS=CE.IDKATIOS AND DRO.IDDIARIO=CE.IDDIARIO 
WHERE PRE.IDKATIOS=@IDKATIOS 
AND PRE.PRODUCTO NOT IN ('Venta Cuota Creciente','Venta de Flujos')
AND (CASE WHEN @TConsulta='FECHA_EFECTIVA' THEN CAST(DRO.FECHAEFECTIVA AS DATE) WHEN @TConsulta='FECHA_APLICACION' THEN CAST(DRO.FECHADIA AS DATE) END) BETWEEN @FECHAINICIAL AND @FECHAFINAL
AND PRE.CTIVO>0
ORDER BY  DRO.FECHADIA

INSERT INTO #AplicacionPagosTemporal
SELECT
DRO.FECHADIA AS 'FECHA_APLICACION'
,PRE.CTIVO AS 'CREDITO'
,PER.NDOC AS 'DOCUMENTO'
,PER.NOMBRES AS 'TITULAR'
,CASE WHEN DRO.Dato2='APL_SALDOS' THEN 'APLICACION SALDOS' WHEN DRO.Dato2='APLSALDOS' THEN 'APLICACION SALDOS' ELSE ISNULL((SELECT TOP 1 NOMBRECUENTA FROM CONTADETALLE WITH(NOLOCK) WHERE IDKATIOS=PRE.IDKATIOS AND IDDIARIO=PE.IDDIARIO AND (CUENTACONTABLE LIKE '238095%' OR CUENTACONTABLE LIKE '%189520%' OR CUENTACONTABLE LIKE '%519595%' OR CUENTACONTABLE LIKE '%111005%' OR CUENTACONTABLE LIKE '%112005%' OR CUENTACONTABLE LIKE '%280505%'  OR CUENTACONTABLE LIKE '%839595%' ) ),'AJUSTE') END AS 'CUENTA_RECAUDO' 
,DRO.FECHAEFECTIVA AS 'FECHA_PAGO'
,CASE WHEN ISNULL(IIF(RTRIM(LTRIM(TX.DESCRIPCION))='SCONTRA','PAGAR',TX.DESCRIPCION),'')='SALDO A FAVOR' THEN 'CXP RENTEK' ELSE ISNULL(IIF(RTRIM(LTRIM(TX.DESCRIPCION))='SCONTRA','PAGAR',TX.DESCRIPCION),'') END AS 'TRANSACCION'
,ISNULL(PLQ.CONDONACION,0) AS 'VALOR_PAGADO'
,ISNULL(CPAG.CONDONACION,0) AS 'KPAGADO'
,ISNULL(IPAG.CONDONACION,0) AS 'IPAGADO'
,ISNULL(SPAG.CONDONACION,0) AS 'SEGURO'
,ISNULL(MPAG.CONDONACION,0) AS 'MORA'
,ISNULL(GCPAG.CONDONACION,0) AS 'GASTOS_DE_COBRANZA' 
,ISNULL(IVGPAG.CONDONACION,0) AS 'IVAGAC' 
,ISNULL(CPG.CONDONACION,0) AS 'CXCPGRACIA'
,ISNULL(SAFPAG.CONDONACION,0) AS 'SAFAVOR'
,ISNULL(CRT.CONDONACION,0) AS 'RUNT' 
,ISNULL(CGM.CONDONACION,0) AS 'GARANTIAS_MOBILIARIAS' 
,ISNULL(CIGM.CONDONACION,0) AS 'IVA_GARANTIAS_MOBILIARIAS' 
,ISNULL(GPSP.CONDONACION,0) AS 'GPS_PAGADO'
,ISNULL(CIIN.CONDONACION,0) AS 'I_INICALES' 
,ISNULL(KPV.KPAGADOVENC,0) 'KFACTURADO_VENCIDO'
,ISNULL(KPNV.KPAGADONOVENC,0) 'KFACTURADO_NO_VENCIDO'
,ISNULL(CPAG.CONDONACION-ISNULL(KPV.KPAGADOVENC,0)-ISNULL(KPNV.KPAGADONOVENC,0),0) 'KNO_FACTURADO'
,ISNULL(CM.VALOR,0) AS 'CAPITAL_MORA'
,ISNULL(IVE.VALOR,0) AS 'IVENCIDO'
,ISNULL(IFA.VALOR,0) AS 'IFACTURADO'
,(SELECT SUBSTRING(ISNULL((SELECT DISTINCT ' - '+ CAST(convert(varchar(10),DATEADD(M,PD.CUOTA,PRE.FECHAINICIAL), 103) AS VARCHAR(MAX)) FROM PRSTMSENC AS PD WITH(NOLOCK) WHERE PD.IDKATIOS=PRE.IDKATIOS AND PD.IDDIARIO=PE.IDDIARIO FOR XML PATH('')),''),3, 255)) AS 'CUOTAS'
,ISNULL((SELECT TOP(1) PD.ESTADO FROM PRSTMSDETALLE PD WITH(NOLOCK) WHERE PD.IDKATIOS=PRE.IDKATIOS AND PD.IDPRESTAMO=PRE.IDPRESTAMO AND PD.IDDIARIO=DRO.IDDIARIO AND PD.NOMBRECUENTA='IdEstado' ),'ACTIVO') AS 'ESTADO' 
,PRE.SUBESTADO AS 'SUBESTADO'
,ISNULL(EM.EDADMORA,'AL DIA') AS 'EDAD_MORA'
,ISNULL(PRE.PRODUCTO,'') AS 'PRODUCTO'
,ISNULL(CE.CTIVO,'') AS 'CONSECUTIVO'
,ISNULL(DRO.Dato2,'') AS 'REFERENCIA'
,ISNULL(IFIN.VALOR,0) AS 'INT_FINALES'
FROM PRSTMS PRE WITH(NOLOCK)
INNER JOIN PRSTMSENC PE WITH(NOLOCK) ON PRE.IDKATIOS=PE.IDKATIOS AND PRE.IDPRESTAMO=PE.IDPRODUCTO AND PE.IDTRX IN ('5001', '5002', '5003', '5013','5014', '5015','5021','5016') AND PE.REFERENCIA NOT LIKE '%RV%' AND  PE.REFERENCIA NOT IN ('Adicion de observacion de cobranza', 'APLSALDOS') AND PE.IdEncabezado='1'
INNER JOIN DIARIO DRO WITH(NOLOCK) ON PRE.IDKATIOS=DRO.IDKATIOS AND PE.IDDIARIO=DRO.IDDIARIO AND DRO.TIPOTRX<>'RV'
INNER JOIN PERSONAS PER WITH(NOLOCK) ON PRE.IDKATIOS=PER.IDKATIOS AND PRE.NDOC=PER.NDOC
INNER JOIN TRX TX WITH(NOLOCK) ON PRE.IDKATIOS=TX.IDKATIOS AND PE.IDTRX=TX.IDTRX
INNER JOIN #LIQUIDACION LQ WITH(NOLOCK) ON PRE.IDKATIOS=LQ.IDKATIOS AND DRO.IDDIARIO=LQ.IDDIARIO
LEFT JOIN PRSTMSLIQUIDACION PLQ WITH(NOLOCK) ON PRE.IDKATIOS=PLQ.IDKATIOS AND LQ.IDLIQUIDACION=PLQ.IDLIQUIDACION
LEFT JOIN #CAPITALPAGADO CPAG WITH(NOLOCK) ON PRE.IDKATIOS=CPAG.IDKATIOS AND DRO.IDDIARIO=CPAG.IDDIARIO
LEFT JOIN #KPAGADOXCUOTAVENCIDA KPV WITH(NOLOCK) ON PRE.IdKatios=KPV.IDKATIOS AND PRE.IdPrestamo=KPV.IDPRESTAMO AND DRO.IDDIARIO=KPV.IDDIARIO
LEFT JOIN #KPAGADOXCUOTANOVENCIDA KPNV WITH(NOLOCK) ON PRE.IdKatios=KPNV.IDKATIOS AND PRE.IdPrestamo=KPNV.IDPRESTAMO AND DRO.IDDIARIO=KPNV.IDDIARIO
LEFT JOIN #INTERESPAGADO IPAG WITH(NOLOCK) ON PRE.IDKATIOS=IPAG.IDKATIOS AND DRO.IDDIARIO=IPAG.IDDIARIO
LEFT JOIN #INTFINALES IFIN WITH(NOLOCK) ON PRE.IDKATIOS=IFIN.IDKATIOS AND DRO.IDDIARIO=IFIN.IDDIARIO
LEFT JOIN #IVENCIDO IVE WITH(NOLOCK) ON PRE.IdKatios=IVE.IDKATIOS AND PRE.IdPrestamo=IVE.IDPRESTAMO AND DRO.IDDIARIO=IVE.IDDIARIO
LEFT JOIN #IFACTURADO IFA WITH(NOLOCK) ON PRE.IdKatios=IFA.IDKATIOS AND PRE.IdPrestamo=IFA.IDPRESTAMO AND DRO.IDDIARIO=IFA.IDDIARIO
LEFT JOIN #SEGUROPAGADO SPAG WITH(NOLOCK) ON PRE.IDKATIOS=SPAG.IDKATIOS AND DRO.IDDIARIO=SPAG.IDDIARIO
LEFT JOIN #MORAPAGADO MPAG WITH(NOLOCK) ON PRE.IDKATIOS=MPAG.IDKATIOS AND DRO.IDDIARIO=MPAG.IDDIARIO
LEFT JOIN #GACPAGADO GCPAG WITH(NOLOCK) ON PRE.IDKATIOS=GCPAG.IDKATIOS AND DRO.IDDIARIO=GCPAG.IDDIARIO
LEFT JOIN #IVAGACPAGADO IVGPAG WITH(NOLOCK) ON PRE.IDKATIOS=IVGPAG.IDKATIOS AND DRO.IDDIARIO=IVGPAG.IDDIARIO
LEFT JOIN #CXCPGRACIA CPG WITH(NOLOCK) ON PRE.IDKATIOS=CPG.IDKATIOS AND DRO.IDDIARIO=CPG.IDDIARIO
LEFT JOIN #SALDOAFAVORPAGADO SAFPAG WITH(NOLOCK) ON PRE.IDKATIOS=SAFPAG.IDKATIOS AND DRO.IDDIARIO=SAFPAG.IDDIARIO
LEFT JOIN #CXCRUNT CRT WITH(NOLOCK) ON PRE.IDKATIOS=CRT.IDKATIOS AND DRO.IDDIARIO=CRT.IDDIARIO
LEFT JOIN #CXCGARANTIASM CGM WITH(NOLOCK) ON PRE.IDKATIOS=CGM.IDKATIOS AND DRO.IDDIARIO=CGM.IDDIARIO
LEFT JOIN #CXCIVAGARANTIAS CIGM WITH(NOLOCK) ON PRE.IDKATIOS=CIGM.IDKATIOS AND DRO.IDDIARIO=CIGM.IDDIARIO
LEFT JOIN #CXCIINICIALES CIIN WITH(NOLOCK) ON PRE.IDKATIOS=CIIN.IDKATIOS AND DRO.IDDIARIO=CIIN.IDDIARIO
LEFT JOIN #CAPITALMORA CM ON PRE.IDKATIOS=CM.IDKATIOS AND DRO.IDDIARIO = CM.IDDIARIO
LEFT JOIN #EDADMORA EM ON PRE.IDKATIOS=EM.IDKATIOS AND DRO.IDDIARIO = EM.IDDIARIO 
LEFT JOIN #GPSPAGADO GPSP WITH(NOLOCK) ON PRE.IDKATIOS=GPSP.IDKATIOS AND DRO.IDDIARIO=GPSP.IDDIARIO
LEFT JOIN #CXCCGPS CXCGPS WITH(NOLOCK) ON PRE.IDKATIOS=CXCGPS.IDKATIOS AND DRO.IDDIARIO=CXCGPS.IDDIARIO
LEFT JOIN CONTAENC CE WITH(NOLOCK) ON PRE.IDKATIOS=CE.IDKATIOS AND DRO.IDDIARIO=CE.IDDIARIO 
WHERE PRE.IDKATIOS=@IDKATIOS 
AND PRE.PRODUCTO NOT IN ('Venta Cuota Creciente','Venta de Flujos')
AND (CASE WHEN @TConsulta='FECHA_EFECTIVA' THEN CAST(DRO.FECHAEFECTIVA AS DATE) WHEN @TConsulta='FECHA_APLICACION' THEN CAST(DRO.FECHADIA AS DATE) END) BETWEEN @FECHAINICIAL AND @FECHAFINAL
AND PRE.CTIVO>0
ORDER BY  DRO.FECHADIA

USE K003_2
IF OBJECT_ID('tempdb..AplicacionPagos') IS NOT NULL  
BEGIN  
DROP TABLE AplicacionPagos;
END
CREATE TABLE AplicacionPagos (
[FECHA_APLICACION] DATE
,[CREDITO] VARCHAR(100)
,[DOCUMENTO] VARCHAR(100)
,[TITULAR] VARCHAR(500)
,[CUENTA_RECAUDO] VARCHAR(500)
,[FECHA_PAGO] DATE
,[TRANSACCION] VARCHAR(500)
,[VALOR_PAGADO] NUMERIC(18,2)
,[KPAGADO] NUMERIC(18,2)
,[IPAGADO] NUMERIC(18,2)
,[SEGURO] NUMERIC(18,2)
,[MORA] NUMERIC(18,2)
,[GASTOS_DE_COBRANZA] NUMERIC(18,2)
,[IVAGAC] NUMERIC(18,2)
,[CXCPGRACIA] NUMERIC(18,2)
,[SAFAVOR] NUMERIC(18,2)
,[RUNT] NUMERIC(18,2)
,[GARANTIAS_MOBILIARIAS] NUMERIC(18,2)
,[IVA_GARANTIAS_MOBILIARIAS] NUMERIC(18,2)
,[GPS_PAGADO] NUMERIC(18,2)
,[I_INICALES] NUMERIC(18,2)
,[KFACTURADO_VENCIDO] NUMERIC(18,2)
,[KFACTURADO_NO_VENCIDO] NUMERIC(18,2)
,[KNO_FACTURADO] NUMERIC(18,2)
,[CAPITAL_MORA] NUMERIC(18,2)
,[IVENCIDO] NUMERIC(18,2)
,[IFACTURADO] NUMERIC(18,2)
,[CUOTAS] VARCHAR(MAX)
,[ESTADO] VARCHAR(500)
,[SUBESTADO] VARCHAR(100)
,[EDAD_MORA] VARCHAR(500)
,[PRODUCTO] VARCHAR(500)
,[CONSECUTIVO] VARCHAR(500)
,[REFERENCIA] VARCHAR(MAX)
,[INT_FINALES] NUMERIC(18,2)
)
INSERT INTO AplicacionPagos
SELECT
ap."FECHA_APLICACION" AS 'FECHA_APLICACION'
,ap."CREDITO" AS 'CREDITO'
,ap."DOCUMENTO" AS 'DOCUMENTO'
,ap."TITULAR" AS 'TITULAR'
,ap."CUENTA_RECAUDO" AS 'CUENTA_RECAUDO' 
,ap."FECHA_PAGO" AS 'FECHA_PAGO'
,ap."TRANSACCION" AS 'TRANSACCION'
,ap."VALOR_PAGADO" AS 'VALOR_PAGADO'
,ap."KPAGADO" AS 'KPAGADO'
,ap."IPAGADO" AS 'IPAGADO'
,ap."SEGURO" AS 'SEGURO'
,ap."MORA" AS 'MORA'
,ap."GASTOS_DE_COBRANZA" AS 'GASTOS_DE_COBRANZA' 
,ap."IVAGAC" AS 'IVAGAC' 
,ap."CXCPGRACIA" AS 'CXCPGRACIA'
,ap."SAFAVOR" AS 'SAFAVOR'
,ap."RUNT" AS 'RUNT' 
,ap."GARANTIAS_MOBILIARIAS" AS 'GARANTIAS_MOBILIARIAS' 
,ap."IVA_GARANTIAS_MOBILIARIAS" AS 'IVA_GARANTIAS_MOBILIARIAS' 
,ap."GPS_PAGADO" AS 'GPS_PAGADO'
,ap."I_INICALES" AS 'I_INICALES' 
,ap."KFACTURADO_VENCIDO" AS 'KFACTURADO_VENCIDO'
,ap."KFACTURADO_NO_VENCIDO" AS 'KFACTURADO_NO_VENCIDO'
,ap."KNO_FACTURADO" AS 'KNO_FACTURADO'
,ap."CAPITAL_MORA" AS 'CAPITAL_MORA'
,ap."IVENCIDO" AS 'IVENCIDO'
,ap."IFACTURADO" AS 'IFACTURADO'
,ap."CUOTAS" AS 'CUOTAS'
,ap."ESTADO" AS 'ESTADO' 
,ap."SUBESTADO" AS 'SUBESTADO'
,ap."EDAD_MORA" AS 'EDAD_MORA'
,ap."PRODUCTO" AS 'PRODUCTO'
,ap."CONSECUTIVO" AS 'CONSECUTIVO'
,ap."REFERENCIA" AS 'REFERENCIA'
,ap."INT_FINALES" AS 'INT_FINALES'
FROM #AplicacionPagosTemporal ap
